### PR TITLE
CHT sensor refactoring

### PR DESCRIPTION
**Pull request by NonPIayerCharacter**
fixed negative temperature on CHT8310 (earlier was treated as unsigned byte)
add CHT8315 (have no device to test, waiting for response on elektroda)
build driver for bl602

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hello, is it ready to merge? @divadiow  are you able to check any of this?

**Comment by divadiow** [comment]
I can only test on CHT8310. but: https://www.elektroda.com/rtvforum/viewtopic.php?p=21108522#21108522

**Comment by divadiow** [comment]
is this good or is more testing required?

**Comment by NonPIayerCharacter** [comment]
Alert appears to be working as expected. Executing CHT_Alert 0.3 5 2 right before PinDeepSleep, the module wakes up, as soon as temperature is 0.3 degrees lower or higher, than last reading.
Ready to merge i believe.

**Comment by openshwprojects** [comment]
Thank you, I don't have ability to test it but I will merge it anyway. Hopefully it was tested well.

**Review by openshwprojects — APPROVED** [review]

**Pull request merged**
