### PR TITLE
feat: add W600 auto build

### PR DESCRIPTION
**Pull request by talltechdude**
Adding W600 build to automated build and releases

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thanks, did you manage to make it work without any changes to parent SDK?

**Comment by talltechdude** [comment]
> Thanks, did you manage to make it work without any changes to parent SDK?

Just using the SDK submodule already added to the main repo (the direct link to https://github.com/iprak/OpenW600) - no other changes were needed and seems to compile successfully.

Did you want this changed to the @openshwprojects fork instead if you're using that instead now?

**Comment by openshwprojects** [comment]
Thanks

@talltechdude , @btsimonh  has recently added CPP support and IR library, but despite the local compilation going great, it seems that online Github compile fails. It looks like it's trying to feed a CPP file like a .o file. Do you know where to look for an error? 
image
You can see it happens on latest commit.
Where is the "../toolchain/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-gcc  -g -Wl,--gc-sections -marm -mcpu=arm96" command  called? Any ideas how to fix? Thanks

**Comment by btsimonh** [comment]
most likely it's checking out a specific commit of the SDK repo?

**Comment by btsimonh** [comment]
yes - there is some procedure to update the submodules in the APP repo, and then commit the new repository point which it is linked to.  I don't remember the details, but basically it's a git thing you need to do....  currently it's referencing a specific commit of the SDK in the app repo?
I thought maybe we had a .sh for that?

**Comment by btsimonh** [comment]
try latest update on my branch?
pure cmd line git is here: 
https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-update-Git-submodules

sourcetree method here:
https://stackoverflow.com/questions/12899163/where-is-git-submodule-update-in-sourcetree
(just double click the submodule).

**Comment by btsimonh** [comment]
Also fixed a case sensitive header file reference :(.
Awaiting git rebuild (on my fork).

**Comment by openshwprojects** [comment]
I assumed it's done automatically now?

I am trying "submodule update --remote" but it seems to be downloading the other repos on my disk to the App dir, which not what I wanted

**Comment by btsimonh** [comment]
just merge new PR :).
builds for T, and all others except N.

**Comment by talltechdude** [comment]
Ah, that makes sense that its not auto-updating the new repos, they were missing from the Makefile. 

PR here https://github.com/openshwprojects/OpenBK7231T_App/pull/319 to hopefully resolve that moving forward and keep them auto-updated to `master` for each SDK

**Pull request merged**
