### PR TITLE
nicer Config page button text

### PR DESCRIPTION
**Pull request by divadiow**
just seeing what these look like in real life

### CODE REVIEW

**Comment by divadiow** [comment]
image
not necessarily proposals, just posting ideas

**Comment by divadiow** [comment]
minimal
image

**Comment by divadiow** [comment]
image

**Comment by openshwprojects** [comment]
There is one problem with that - we have many guides/posts saying "and click buttom XYZ" and if we change the names it will be invalidated :D

**Comment by divadiow** [comment]
yes! I was just thinking that :( :(

**Comment by divadiow** [comment]
and documentation

**Comment by divadiow** [comment]
just trying things 
image

**Pull request closed without merging**
