### PR TITLE
Added new files for 183

### PR DESCRIPTION
**Pull request by iprak**
This PR is in preparation for #183 (which I will revise). This includes some new files which would be used in #183.

Here are the other associated merge requests:
* BK7231T - sdk\include\cJSON.h has been commented out to prevent build errors. https://github.com/openshwprojects/OpenBK7231T/pull/7
* W800 - this SDK had an older cJSON. The Makefile has been adjusted to include new .cs files and skip building SDK cJSON component https://github.com/openshwprojects/OpenW800/pull/2.
* XR809 - same changes as W800 https://github.com/openshwprojects/OpenXR809/pull/3

### CODE REVIEW

**Comment by iprak** [comment]
This merge should verify that builds are successful with adjustments to other sdks. The cJSON component is not used anywhere.

**Comment by openshwprojects** [comment]
Is it ready to merge? What is the merge order you need?
Thanks!

**Comment by iprak** [comment]
Yes.

The SDK requests should be merged first. I am assuming that OpenBK7231T_App will pull updated content to its sub-modules when this merge takes place.

**Comment by openshwprojects** [comment]
Thank you, so I am adding those pull requests now.

**Pull request merged**
