### PR TITLE
Deepsleep

### PR DESCRIPTION
**Pull request by Dheenhasty**
Adding GPIO DeepSleep compatibility for Platform N 

SDK need to be merge before merging this one. 
https://github.com/openshwprojects/OpenBK7231N/pull/15

### CODE REVIEW

**Comment by openshwprojects** [comment]
hey, is this ready to merge? thanks

**Comment by Dheenhasty** [comment]
Not until sdk is up to date.

**Comment by openshwprojects** [comment]
This is bad:
image
I already fixed it by including a header... but I will merge it now and fix myseelf.

**Comment by Dheenhasty** [comment]
> 

Sorry for that seems like my commit include old code from the cmd .....

**Pull request merged**
