### PR TITLE
Add HTTP basic authentication

### PR DESCRIPTION
**Pull request by castorw**
This PR adds HTTP basic authentication to OpenBK web application. I believe having protected administrative interface is a must for all managed devices. The following is done:
* [X] Added Base64 lib to source (required for processing of `Authorization` header),
* [X] Added `webPassword` to config for platforms with sufficient config block size,
* [X] Bumped config version to `5` to properly migrate (empty) web password if necessary,
* [X] Add `http_basic_auth` mechanism,
* [X] Added `auth_required` flag for HTTP callbacks,
* [X] Protected all web admin pages,
* [X] Protected API, logging endpoints,
* [X] Kept integration endpoints unauthenticated (at least for now).

@openshwprojects The following build problems remain:
* SDKs need to be updated for `OpenXR809`, `OpenW800`, `OpenW600` to include:
  * `base64/base64`
  * `httpserver/http_basic_auth`
  * *(other option would be to pack it all within `httpserver/new_http.c`)*
* `OpenBK7231T` build succeeds locally using docker build, but fails with random return code in GH Actions,
* `OpenBL602` build is failing for some other unrelated error.

Please consider merging this into upstream.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Very good job! I can update the SDKs for you today, assuming you've opened the PRs for them as well.
I am aware about T build random problem, I tried investigating it yesterday, results here:
https://github.com/openshwprojects/OpenBK7231T_App/issues/987
I will try to review it soon and test, I want to have it merged soon. Thanks!

**Comment by castorw** [comment]
@openshwprojects I will create PRs later today. Also I will fine-tune WebUI config for web password so it's more readable to users.

**Comment by castorw** [comment]
I have updated the UI:
* Renamed "Configure WiFi" to "Configure WiFi & Web"
* Added some info text
* Added checkbox to explicitly enable/disable the feature

Here are SDK PRs:
* https://github.com/openshwprojects/OpenW600/pull/10
* https://github.com/openshwprojects/OpenW800/pull/6
* https://github.com/openshwprojects/OpenXR809/pull/6

@openshwprojects Will you update submodules in app repo?

**Comment by openshwprojects** [comment]
I will update, but how is the flash usage now? BL602 OTA breaks if file is too large. Is there an easy way to disable web security, maybe in obk_config.h ? I saw you had a define in config structure itself

**Comment by openshwprojects** [comment]
submodules have been updated

**Comment by castorw** [comment]
I have just updated submodules in my branch, let's see how the builds go. I will check on the BL602 as well. And currently there is no way to disable it globally.

**Comment by castorw** [comment]
@openshwprojects Ok I have fixed build for BL602 as well. I believe this is the information you are seeking:
```
[bl_mfg_ota_xz_gen] the size of FW_OTA.bin data (file_bytes) is 763184
[bl_mfg_ota_xz_gen]  Generating BIN File to /home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenBL602/customer_app/bl602_sharedApp/build_out/ota/dts40M_pt2M_boot2release_ef7015/FW_OTA.bin.xz
[bl_mfg_ota_xz_gen] the size of xz data (after compression) is 405960
[bl_mfg_ota_xz_gen] the size of fw_ota_bin_xz_ota data (with header) is 406472
[bl_mfg_ota_xz_gen]  Generating BIN File to /home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenBL602/customer_app/bl602_sharedApp/build_out/ota/dts40M_pt2M_boot2release_ef7015/FW_OTA.bin.xz.ota
[bl_write_flash_img] whole_img_data size is 2070055
```

Except for the BK7231T build everything seems to be OK.

**Comment by openshwprojects** [comment]
So it's enabled on T and N for now?
Have you tested updating?
It will not lock people's devices?

**Comment by castorw** [comment]
It should be enabled on all platforms except W600 and W800.
I will try updating this evening and let you know - I only have BK7231N hardware on hand though.

**Comment by castorw** [comment]
@openshwprojects I have tried updating BK7231N Smart Plug from previous release version (1.17.335) to current devel and everything worked out fine. Device has booted and I was able to configure web password.

**Comment by openshwprojects** [comment]
seems to work on N, i must get a T test board. I dont want to accidentally brick any boards....

this will keep web admin password even in safe mode?

**Comment by ataa** [comment]
Just tested it, I had to enable it on BK7231N based down light (upgraded from 6 month old firmware). 
Working as expected. Thank you.

**Comment by castorw** [comment]
@openshwprojects Yes it currently also runs in safe mode. Actually I would keep this behaviour since safe mode creates an open AP which can be joined by anyone and possibly allow them to control sensitive devices.

However, if you would like to have safe mode clean without auth - I can change it right away - let me know .

**Comment by openshwprojects** [comment]
would it be possible to add a checkbox/flag like "Enable also web password in safe mode"?

**Comment by castorw** [comment]
@openshwprojects Added as flag `Flag 44 - [HTTP] Disable authentication in safe mode (not recommended)`. It is by default disabled and therefore authentication is enabled even in safe mode. Users may opt out by setting this flag.

**Comment by openshwprojects** [comment]
@castorw  love it! Good job. Now, I will merge it tomorrow morning, but would you like to create some kind of short guide for extreme beginners, with screenshots, and poost it to our tutorials section?
https://www.elektroda.com/rtvforum/forum517.html
We can send you a free gift for that.
https://www.elektroda.com/rtvforum/topic3950844.html

**Comment by castorw** [comment]
@openshwprojects Do you know the version for tomorrow release? So I can mention it in the tutorial.

Also there is an issue with BL602 build, fixing it now.

**Comment by openshwprojects** [comment]
Well, there is no hurry, you can write tutorial for few days or so....  if you are not sure about something, then dont worry, most likely forum engine will move your post ot "Temporary posts" so I will be able to review it before it goes public. 

Tutorial can be posted after tomorrow release (and I can modify it if something is missing), just try to give step by step guidance, like for a non-technical people, thanks!

I will make relaese tomorrow and manually add T platform build, because it's still broken, somehow....

**Comment by castorw** [comment]
@openshwprojects BL602 build has been fixed.

**Comment by DeDaMrAzR** [comment]
Just to chime in, tested on Both N and T platforms and works as expected.

**Comment by openshwprojects** [comment]
The OTA for T breaks LFS, it may have something to do with RBL fiel size, but let's investigate it separately. Or do you know anything about it @castorw ?

**Comment by castorw** [comment]
@openshwprojects Are we sure it's caused by this update? Couldn't this be related to something else.
@DeDaMrAzR could you possibly check if your LFS storage on T gets corrupted during upgrade?

I didn't expand any data structure within my modifications.

As for the RBL size:
* (original) OpenBK7231T_1.17.335.rbl is `498416` bytes,
* (updated) OpenBK7231T_dev_20231213_084559.rbl is `500048` bytes.

So there is a slight increase. Don't know if this could cause any issues.

According to `BkDriverFlashFiles.c` the N platform should have `664KB` for OTA and the T platform should have `600KB` for OTA.

`OpenBK7231T_App/sdk/OpenBK7231T/platforms/bk7231t/bk7231t_os/beken378/func/user_driver/BkDriverFlash.c`:
```
...
    [BK_PARTITION_OTA] = 
    {
        .partition_owner           = BK_FLASH_EMBEDDED,
        .partition_description     = "ota",
        .partition_start_addr      = 0x132000,
        .partition_length          = 0x96000, //600KB
        .partition_options         = PAR_OPT_READ_EN | PAR_OPT_WRITE_DIS,
    },
...
```

`OpenBK7231T_App/sdk/OpenBK7231N/platforms/bk7231n/bk7231n_os/beken378/func/user_driver/BkDriverFlash.c`:
```
...
    [BK_PARTITION_OTA] = 
    {
        .partition_owner           = BK_FLASH_EMBEDDED,
        .partition_description     = "ota",
        .partition_start_addr      = 0x12A000,
        .partition_length          = 0xA6000, //664KB
        .partition_options         = PAR_OPT_READ_EN | PAR_OPT_WRITE_DIS,
    },
...
```

**Comment by castorw** [comment]
I looked through the LFS init code:
```c
void init_lfs(int create){
    if (!lfs_initialised){
        uint32_t newsize = CFG_GetLFS_Size();

        // double check again that we're within bounds - don't want
        // boot overwrite or anything nasty....
        newsize = (newsize/LFS_BLOCK_SIZE)*LFS_BLOCK_SIZE;
        if ((newsize < LFS_BLOCKS_MIN_LEN) || (newsize > LFS_BLOCKS_MAX_LEN)) {
            ADDLOGF_ERROR("LFSSize OUT OF BOUNDS 0x%X (range 0x%X-0x%X) - defaulting to 0x%X", 
                newsize,
                LFS_BLOCKS_MIN_LEN,
                LFS_BLOCKS_MAX_LEN,
                LFS_BLOCKS_DEFAULT_LEN
                );
            newsize = LFS_BLOCKS_DEFAULT_LEN;
        }
        uint32_t newstart = (LFS_BLOCKS_END - newsize);

        if (newstart < LFS_BLOCKS_START_MIN){
            ADDLOGF_ERROR("LFS OUT OF BOUNDS start 0x%X too small", newstart);
            return;
        }
        if ((newstart + newsize > LFS_BLOCKS_END) ||
            (newstart + newsize < LFS_BLOCKS_START_MIN)){
            ADDLOGF_ERROR("LFS OUT OF BOUNDS end 0x%X too big", newstart + newsize);
            return;
        }
...
```

And if `LFS_BLOCKS_DEFAULT_LEN` equals `0x8000` (32768), then for BK8231T platform there should be `0x8E000` (581632 = 568kB) left for OTA which does not come near the 488kB the new RBL has. **LFS issue could arise if the default LFS size is altered in configuration.** Otherwise I don't think the size of this update should break LFS.

**Comment by openshwprojects** [comment]
Okay, let's give it a chance, In worst case we'll fix LFS separately.

I will merge it now, thank you, @castorw ! If you have any questions regarding the tutorial (if you've decided to do it) ping me here or maybe open separate issue or just msg me on forums.

PS: I will manually add T build later...

**Comment by castorw** [comment]
@openshwprojects Here is the written tutorial: https://www.elektroda.com/rtvforum/topic4021160.html. I believe you need to approve it and move it to the proper section.

**Comment by mmbarki** [comment]
Hi, is it possible to have the same BasicAuth on W600 platform?  
Thank you.

**Pull request merged**
