### PR TITLE
IR Tx without IR RX

### PR DESCRIPTION
**Pull request by btsimonh**
allows IR tx when RX is not present.

### CODE REVIEW

**Comment by btsimonh** [comment]
Ready to merge when build succeeds.
To merge into main, pull to local, merge to main and push?
Or create another PR directly against main...

**Comment by btsimonh** [comment]
Adds:
IREnable RXTX 0/1 - enable/disable rx whilst tx.  default disabled.
IREnable [protocol name] 0/1 - enable/disable protocol RX.  default all enabled.
made many logs DEBUG.
You will get at least one log at INFO on RX.

e.g. IREnable NEC 0 - stops rx of NEC protocol.

**Comment by btsimonh** [comment]
wait, one more thing to change.
backlog IRSend NEC-0xC2EA-0x19; IRSend NEC2-0xC2EA-0x99
does not wait between sends...

**Comment by btsimonh** [comment]
Now it's done.
100ms inserted after any command sequence.
added IREnable invert 1 to use active high on output?

**Comment by lippertmarkus** [comment]
works great for me

**Pull request merged**
