### PR TITLE
Generate better uniqued id, fixed payload

### PR DESCRIPTION
**Pull request by iprak**
* Updated `unique_id` based on https://developers.home-assistant.io/docs/entity_registry_index/
* Also updated on/off payload  #138

### CODE REVIEW

**Comment by pretoriano80** [comment]
@iprak i think that would be a better practice to split this in two PRs,one PR for each issue/bug fix.
It's easier to keep track of the changes and also easier if a revert it's required .

**Comment by iprak** [comment]
> @iprak i think that would be a better practice to split this in two PRs,one PR for each issue/bug fix. It's easier to keep track of the changes and also easier if a revert it's required .

That is a good idea. I will try to keep that in mind for future merges. :-)

**Comment by openshwprojects** [comment]
The idea is good but I need you to fix the memory leak, because you are doing "malloc" and not freeing the memory.

The best solution would to be put something like char buffer[128];  into the function generating config and just operate on that

**Comment by openshwprojects** [comment]
One more fix - having:

char *getSmth() {
  char smth[127];
  strcpy(smth,"qqq");
  return smth;
}

void tst() {
  char *a = getSmth();
}

is not a correct practise, because C does not guarante that the buffer will still exist after returning from the function. This is like a russian roulette crash. The contents of smth are undetermined after returning from function.

You should rather do:

void getSmth(char *outBuffer, int bufferLen) {
  strcpy(smth,"qqq"); // better use safe strcpy
}

void tst() {
 char bufferToUse[256];
  getSmth(bufferToUse,sizeof(bufferToUse));
}

**Pull request merged**
