### PR TITLE
MQTT, OTA changes

### PR DESCRIPTION
**Pull request by valeklubomir**
MQTT - fix for timestamp for HA discovery. Checking OTA running process, MQTT will disconnect automatically. MQTT benchmark added. 
DRV - Fix generation of last clearing date. MQTT connection check before publishing.
NTP - retab formatting. Checking OTA running process, which stops next NTP check. TZ export
OTA - minor optimization. Faster version.

Tested device N,T
Pull request for OpenBK7231T

### CODE REVIEW

**Comment by openshwprojects** [comment]
Very good improvement, but can you take a look here?
image
Shouldn't' it be == true?

**Comment by valeklubomir** [comment]
@openshwprojects you are right. 
Will fix it.

**Comment by openshwprojects** [comment]
Ok, I'm eager to merge it. Is it ready now?

**Comment by valeklubomir** [comment]
Yes. If you did not found more. I checked it again. Should be OK now.

**Pull request merged**
