### PR TITLE
Adding SGP Air Sensor I2C Driver

### PR DESCRIPTION
**Pull request by Dheenhasty**

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hmm this issue has been already fixed:
#Adding dependency in drv_tuyaMCU for bl0602
Apart from that, it looks good and can be merged

**Comment by Dheenhasty** [comment]
I suppose i have resync the branch just before your correction.

Thanks for the merge :)

**Comment by Dheenhasty** [comment]
Any issue to merge it ?

**Comment by openshwprojects** [comment]
Please resolve conflicts and I will merge it ASAP.

**Comment by Dheenhasty** [comment]
Should be ok :)

**Comment by openshwprojects** [comment]
Thanks, but next time try to commit only code changes, no whitespace etc changes, because they make it harder to review.

is there a guide for SGP driver on Elektroda already?

**Pull request merged**
