### PR TITLE
Pin cfg: Sort Driver / pin function list alphabeticaly

### PR DESCRIPTION
**Pull request by MaxineMuster**

### CODE REVIEW

**Comment by divadiow** [comment]
ooh yeh. that's gorgeous 
image

**Comment by divadiow** [comment]
pin assignment test 
image

**Comment by divadiow** [comment]
nice 
image

**Comment by DeDaMrAzR** [comment]
This one looks to be working alright and is probably OK to merge, tested on N and T modules.

**Comment by divadiow** [comment]
great stuff

**Comment by divadiow** [comment]
image

**Pull request merged**
