### PR TITLE
adding 3 command SetupSHT3X to calibrate sensor and Battery_measure 

### PR DESCRIPTION
**Pull request by Dheenhasty**
Adding 2 new command : 
  - SetupSHT3X dependent of sht3x driver permit to calibrate the sensor 
    Ex : SetupSHT3X 4 -10 // it will remove 4 degrees to Temperature and add 10% to humidity.

  - Battery_measure : 
     It will calculate and publish voltage and battery percentage base on min battery and max battery in args. 
     The calculation is based on Tuya SDK ( /4096 * 2400 ) of ADC. (IOR_ADC must be assigned)
     mqtt topic => voltage and battery
     Ex : Battery_measure 1500 3000 // will give you the percentage of battery based on this 2 value.

### CODE REVIEW

**Comment by Dheenhasty** [comment]
Please do not merge this for the moment, i will add another method to measure the sht3x temp.

**Comment by openshwprojects** [comment]
Ok ok I just wanted to review it, but i I will wait

**Comment by Dheenhasty** [comment]
Ok needed a rebase, and adding all SHT Command except the Alert one (will work on it)

based on sensor capacity : 

SHT_Calibrate => to calibrate before measurement
SHT_Measure => to do one shot measure
SHT_LaunchPer => to launch internal sensor periodic capture
SHT_MeasurePer => to fetch the periodic data captured
SHT_StopPer => to stop periodic capture
SHT_Heater => to activate/deactivate Heater
SHT_GetStatus => retrieve the sensor Status

Battery_measure => Get ADC Stats.

**Comment by openshwprojects** [comment]
Hey, is it ready to merge? Can you fix conflicts?

**Comment by Dheenhasty** [comment]
Hello, all command work. except the battery measurement. it only works when battery is under 2,4v 
We can merge it. as suggested in Forum i will try to work on improvement regarding the heater (to be able to commande it thru onchannelchanged. )

**Pull request merged**
