### PR TITLE
Publish IP and SSID to Home Assistant

### PR DESCRIPTION
**Pull request by CrewMdk**
### Before:
Before
### After:
After

### CODE REVIEW

**Comment by openshwprojects** [comment]
The idea is very good and I will accept that, but for the reboot reason, you need to make a separate function instead of copying/pasting code from main.

**Comment by rpv-tomsk** [comment]
Hi, can you please point me, where IP/SSID values are passed to JSON fields ?

**Comment by openshwprojects** [comment]
The SSID2 PR is awaiting for feedback from you guys, I need to now whether it's stable first.

This one I can merge now, thanks.

**Review by openshwprojects — APPROVED** [review]

**Comment by rpv-tomsk** [comment]
Updated my device (BL602 based), see new info in Home Assistant.

**Pull request merged**
