### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by iprak**
Introduced settings for VSCode so that we can consistent tab/spacing.

The formatting is via  `ms-vscode.cpptools` extension and based on the default `LLVM` style. I kept tabSize of 4 and inserSpaces which also were the defaults.

And formatted a bunch of files in httpserver folder.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Nice, just make sure that indenting is done by TAB, as it's the way that works bests in the IDEs that I use.

**Comment by iprak** [comment]
I used spaces but have switched it to Tab.

**Comment by openshwprojects** [comment]
Hm, it seems that conflicts must be resolved first

**Comment by openshwprojects** [comment]
We have a problem:
"[2:09:38 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://x-access-token:[secure]@github.com/iprak/OpenBK7231T_App.git
Error: Error: Command failed with exit code 1: git push --tags ***github.com/iprak/OpenBK7231T_App.git"
Hmmm maybe those links should point to the main repo and not the fork

**Comment by openshwprojects** [comment]
Not because this build had W600 built:
https://github.com/openshwprojects/OpenBK7231T_App/releases/tag/1.14.1

**Comment by iprak** [comment]
I looked at the Actions page https://github.com/openshwprojects/OpenBK7231T_App/actions

* #666 This was just Readme update so there was no release
* #665 workflow for PR #280 skipped Sematic Release Job completely.
* #664 workflow for PR #282 generated a release

My PRs should not have impacted the workflows, My PR did not touch .github)/workflows file.

I can fix the conflicts on this PR and then we can see what happens.

**Comment by iprak** [comment]
Great, you found the cause. I never would have thought it was in packages.json

**Comment by iprak** [comment]
I checked and the formatting settings are the same as of VS (2022).

**Comment by openshwprojects** [comment]
Yes, package file was seen and checked by Github. Ok, I will merge it now, can you look into  https://github.com/openshwprojects/OpenBK7231T_App/issues/279 ?

**Comment by iprak** [comment]
Will do

**Pull request merged**
