### PR TITLE
improve DS1820 logging

### PR DESCRIPTION
**Pull request by MaxineMuster**

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hey, is it tested and ready to merge?

**Comment by MaxineMuster** [comment]
The fix was not needed (turned out to be another issue), but we might keep the updated logging.

I can't do some tests now, will report back in some days.

**Comment by divadiow** [comment]
I can test, but any test in particular? Just connect up and post some cmd logs?

**Comment by MaxineMuster** [comment]
Thanks, it's indeed just checking the logs, if all hex values are now in the same format 0xXX (always two values after 0x)

**Comment by NonPIayerCharacter** [comment]
Does negative temperature works alright in the latest builds? I have a battery sensor with waterproof DS18B20 cable soldered onto it (so probably a clone), but in HA, for the last several days, every temperature reading reported is -0.01.

**Comment by divadiow** [comment]
> Thanks, it's indeed just checking the logs, if all hex values are now in the same format 0xXX (always two values after 0x)

[BK-N.txt](https://github.com/user-attachments/files/17643360/BK-N.txt)
I can do other platforms later today if desired

**Comment by MaxineMuster** [comment]
I'll check again but negative temperatures should work.
Can you check the readings on main page or in the logs to see whether it is related to the temperature reading, the assignment to the channel or the publishing of the values?

**Comment by divadiow** [comment]
shoved mine in freezer
image
```
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1912, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-13.-7
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1928, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-94
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1936, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-88
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1944, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-82
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1960, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-69
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1968, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-63
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-1976, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-14.-57
```

**Comment by divadiow** [comment]
**1394_merge_c5cfa0c6b801**
```
Info:SENSOR:DS1820[7] - Starting conversion
Error:SENSOR:DS1820[7] - Read Reset failed
Debug:SENSOR:DS1820[7] - family=28, raw=-2088, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-31
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-2088, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-31
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-2088, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-31
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-2088, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-31
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-2096, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-37
Info:SENSOR:DS1820[7] - Starting conversion
Debug:SENSOR:DS1820[7] - family=28, raw=-2096, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[7] - Temp=-15.-37
```
image

**Comment by MaxineMuster** [comment]
:-( will try again later with a little more time...

**Comment by MaxineMuster** [comment]
looks o.k. now for me:

grafik


But will need to do it again, to resolve the conflicts after ESP-Update including DS1820 code ..

**Comment by MaxineMuster** [comment]
New PR #1416

**Comment by MaxineMuster** [comment]
@NonPIayerCharacter 
>  for the last several days, every temperature reading reported is -0.01.
Have you been able to fetch some more information?

I think it might also be an issue if reading the sensors temperature failed, because in this case the last read value is kept and will be sent repeadtedly.

We maybe should "invalidate" the temperature after some time, which has to be defined: 
After one failed reading I would assume it's o.k. to keep the previous temperature
After one day or even one hour this is probably not the expectation

Maybe 5 minutes? or even one minute?

Can (how) MQTT handle "invalid" or non present values?  
What happens with other sensors if a reading fails? DHT ??

**Pull request closed without merging**
