### PR TITLE
Add energy sensors to MQTT + HA discovery for active power, reactive power, power factor

### PR DESCRIPTION
**Pull request by stefan064**
For #1097 
And 'energy 2 days ago', 'energy 3 days ago'.
Also added discovery for diagnostic RSSI and uptime as already published on mqtt.
I'm still testing this carefully after refactoring in `drv_bl_shared.c` and don't consider it ready as yet, but keen on feedback and help with testing.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Not bad, I think I will be happy to merge it, but it needs to be tested well. Maybe I should extend the self test system. it is important not to break the other features...

**Comment by stefan064** [comment]
Thank you, appreciate your concern. I've fixed a few minor things but otherwise looking good so far.

**Comment by openshwprojects** [comment]
Do you think it's safe to merge?

**Comment by stefan064** [comment]
Yes please I feel it's safe for all to try now.
Positive notes:
- MQTT publish thresholds and intervals appear to be respecting their settings.
- 'periodic statistics' works as before.
- Units and Wh to kWh conversions look correct, as with rounding etc.
- Changes appear to go smoothly with existing home assistant device and entity configs.

Other observations:
- Not sure how useful '2 days ago' and '3 days ago' will be for home assistant users; they came as a convenient side effect of my changes.
- I've learnt that 'Energy last hour' isn't really 'last hour' but moreso 'over the sum of periodics statistics'. I left the name as before but just noting here and in some code comments.
- I left the web UI Wh/kWh units as they were instead of making them follow mqtt settings, in case there was some reason for it being this way.

As seen in home assistant, before :
image
And After:
image
Web UI:
image
Thankyou for considering all this.

**Review by openshwprojects — APPROVED** [review]

**Pull request merged**
