### PR TITLE
Correct Float for SHT.

### PR DESCRIPTION
**Pull request by Dheenhasty**

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hey, why floor? I don't think floor is needed. Sprintf can do everything itself, without floor.

**Comment by Dheenhasty** [comment]
- Correct SHT Display Value. 
- Adding possibility to deactivate autostart for all drivers on flag.

**Comment by Dheenhasty** [comment]
Ready to merge

**Comment by Dheenhasty** [comment]
> Hey, why floor? I don't think floor is needed. Sprintf can do everything itself, without floor.

i removed it for a int calculation, a bit overkill maybe, it's just an habit on my side to correct data before showing them.....

**Pull request merged**
