### PR TITLE
LN882H PWM

### PR DESCRIPTION
**Pull request by NonPIayerCharacter**
Requires https://github.com/openshwprojects/OpenLN882H/pull/15
Needs further testing. I tested it only on 1 channel.

### CODE REVIEW

**Comment by openshwprojects** [comment]
thanks! SDK merged, can you update submodules and retry?

**Comment by NonPIayerCharacter** [comment]
Maybe remove pins A13-B2 altogether? They are present only on QFN40, and used for QSPI. I believe they should not be used for gpio at all.

**Comment by divadiow** [comment]
basic question. a decent way to test this would be RGBCW separate LEDs on 5 GPIOs on LN, set PWM1-5 as appropriate per GPIO in OBK, then fiddle with the colour picker/dimmer and web app RGBCW output tools?

**Comment by divadiow** [comment]
it's probably my test but with these set currently only R, C and W light

RED A6 PWM1
GREEN A1 PWM2
BLUE A11 PWM3
COOL B8 PWM4
WARM B9 PWM5

thing is you can then re-assign blue to say B3 and it'll start working, but then warm or cool will stop. Individually all LEDs work. Could well me choosing wrong combination of pins, I know some are default pull-up, so the LED lights dimly when connected as a default state.

These are the options I have with MQ-12F module

image

as of right now with RCW working the warm/cool slider behaves as expected 

image
image
(green only dimly lit because A1 is default PU)

**Comment by divadiow** [comment]
ok. with these set BEFORE A REBOOT

image

Red works
Green always lit
Blue works
Cool not work
Warm works

AFTER REBOOT

Red not work
Green works
Blue not work
Cool works
Warm works

every reboot after that is the same as second list above.

apologies if I'm confusing things and my test is rubbish.

**Comment by NonPIayerCharacter** [comment]
I'm away for several days, so can't test it for now. Will try to connect an rgb led and play with channels, maybe figure out what's wrong. I have a LN-02 module, it should have enough free pins to test. Possibly problem is with ADV_TIMER_x_BASE, you can try to reduce amount of pwm channels in code, so each channel have separate TIMER_BASE.

**Comment by divadiow** [comment]
cool. LN-02 options

image

I don't know why I haven't tried with a reduced number of PWMs set. I could just remove C+W to see if RGB are then fine. I will

> you can try to reduce amount of pwm channels in code, so each channel have separate TIMER_BASE.

I may do if I can work out what this means for the code!

**Comment by divadiow** [comment]
interesting. with C+W unset G and B toggle OK. If you unset B too, leaving only R and G, only G will light BUT using the "100% WARM" button

**Comment by divadiow** [comment]
with only R - PWM 1 - set the green is permanently lit but red does toggle

**Comment by NonPIayerCharacter** [comment]
try https://github.com/openshwprojects/OpenBK7231T_App/pull/1331
max channels - 5

**Comment by divadiow** [comment]
oh cool. will do. ChatGPT and I are playing too https://github.com/openshwprojects/OpenLN882H/pull/16/files

**Pull request merged**
