### PR TITLE
HomeAssistant MQTT Discovery

### PR DESCRIPTION
**Pull request by iprak**
This merge implements HA MQTT Discovery (https://github.com/openshwprojects/OpenBK7231T_App/issues/79).

### End User Changes
The `Home Assistant Cfg` page has some new button to send discovery MQTT and configure MQTT. An override discovery topic  can be defined as per https://www.home-assistant.io/docs/mqtt/discovery/.
image

After HomeAssistant has received the discovery message, it should automatically list the device.
image

Along with the discovery payload
image

### Code Changes
* The JSON for discovery is generated using cJSON. The HASS specific functionality is in a new file named `hass.c`.
* Clicking the button queues up this operation. `new_mqtt.c` has been updated to support queuing messages. Up to 3 queued messages are sent out at once. Testing (see later) confirmed that it worked well at least in BK7231T.
* I also added a new MANUFACTURER constant.

The BK7231T SDK has `cJSON.h` in `sdk\include` folder . The file defines redirects to `ty_cJSON_*` functions which are not implemented. This file is referenced by some other files in the same folder. The other platforms (BL602, XR809) have older cJSON implementations in the SDK. I opted to use the latest cJSON codebase and have it be inside `OpenBK7231T_App` so that the outcome is consistent.
* The cJSON library copied from https://github.com/DaveGamble/cJSON (b45f48e600671feade0b6bd65d1c69de7899f2be)  is present in the folder `cJSON`.
*  BK7231T - `sdk\include\cJSON.h` has been commented out to prevent build errors. https://github.com/openshwprojects/OpenBK7231T/pull/7
* BL602 - I modified `bouffalo.mk` as part of this merge to include build of the new cJSON folder.
* W800 - this SDK had an older cJSON. The Makefile has been adjusted to include new .cs files and skip building SDK cJSON component https://github.com/openshwprojects/OpenW800/pull/2.
* XR809 - same changes as W800 https://github.com/openshwprojects/OpenXR809/pull/3

### Testing
I tested creating a fake device with 3 relays which resulted in 3 MQTT messages being sent without any issues.

```
{"dev":{"ids":["enbrighten1_8C000000"],"name":"enbrighten1","sw":"1.0.0","mf":"Beken Corporation","mdl":"BK7231T"},"name":"enbrighten1 3","stat_t":"enbrighten1/3/get","cmd_t":"enbrighten1/3/set","avty_t":"enbrighten1/connected","pl_on":"1","pl_off":"0","uniq_id":"enbrighten1_8C000000_relay_3"}

{"dev":{"ids":["enbrighten1_8C000000"],"name":"enbrighten1","sw":"1.0.0","mf":"Beken Corporation","mdl":"BK7231T"},"name":"enbrighten1 2","stat_t":"enbrighten1/2/get","cmd_t":"enbrighten1/2/set","avty_t":"enbrighten1/connected","pl_on":"1","pl_off":"0","uniq_id":"enbrighten1_8C000000_relay_2"}

{"dev":{"ids":["enbrighten1_8C000000"],"name":"enbrighten1","sw":"1.0.0","mf":"Beken Corporation","mdl":"BK7231T"},"name":"enbrighten1 1","stat_t":"enbrighten1/1/get","cmd_t":"enbrighten1/1/set","avty_t":"enbrighten1/connected","pl_on":"1","pl_off":"0","uniq_id":"enbrighten1_8C000000_relay_1"}
```

### CODE REVIEW

**Comment by openshwprojects** [comment]
Seems like a great update, my only concern is this:
_Clicking the button queues up this operation. new_mqtt.c has been updated to support queuing messages. Up to 3 queued messages are sent out at once. Testing (see later) confirmed that it worked well at least in BK7231T._

there were some stability issues with some N chips that I tried to improve by reducing the number of sent messages. I am not sure how much this pull request will affect that. 

If I merge that it now, would it be possible to easily a) change number of MQTT messages send per update frame b) change back MQTT button event code to send immediatelly (without the queue)?

**Comment by iprak** [comment]
So I did start by sending the MQTT message immediately but ran into some memory issues which ended up due to toolchain implementation of strdup which I which I created a local function _strdup (in new_mqtt,c).

I thought that the chipset is powerful enough to send 3 messages at one but I did notice commits related to MQTT stability. I think only PWM light would have 3 or more entities and based my testing on a device with 3 fake relays. I don't have any other chipsets so could not verify anything else.

a) I have currently hardcoded the iteration max count in the function `PublishQueuedItem` which is defined towards the end of `new_mqtt.c`. I could #define the max count to make adjustments more easy and cleaner.

b) I can add back the helper API `MQTT_PublishTopic` which itself could be useful elsewhere. The caller can then just call it instead of `MQTT_QueuePublish` with same parameters. `MQTT_PublishTopic` publishes one message at a time though.

**Comment by iprak** [comment]
The builds for 3 other chipsets will continue to fail unless those other PRs are merged but build after merging them by themselves might also fail since they refer to files which are being added in this PR. Should I create a separate PR with empty files first ?

**Comment by openshwprojects** [comment]
I can accept changes for SDK right now, just tell me, they don't break anything with current state of things?

**Comment by iprak** [comment]
Need to look into why XR809 build is remotely failing.

**Comment by openshwprojects** [comment]
/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenXR809/tools/gcc-arm-none-eabi-4_9-2015q2/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: cannot find -lcjson

lcjson vs lcJSON - maybe capital letter issue somewhere?

**Comment by iprak** [comment]
This did not seem to be a case issue. The folder `XR809/src/cjson` is not built but cjson was still being linked. Submitted https://github.com/openshwprojects/OpenXR809/pull/4 .. I will push updated XR809 submodule once that is merged. Hopefully that is the last of these build errors.

**Comment by openshwprojects** [comment]
Ok, merged. Thanks.

**Comment by iprak** [comment]
@openshwprojects Any more feedback about this?

**Comment by dskw** [comment]
Hi, I've tested your build on a new Nous A1. Autodiscovery works as intended for the relay/switch state, but does not include any voltage or other power topics.

Is there any way to configure the auto discovery to pick up the power measurements too?

**Comment by iprak** [comment]
Yes, it would be possible to include voltage/current/power states in discovery and I can look into that separately after this merge.

**Comment by openshwprojects** [comment]
#define MQTT_PUBLISH_ITEM_VALUE_LENGTH    480
it's pretty lenghty, do we need that large values?

Aside from that, I think we will merge it soon and just see what happens. There are some rare edge cases on N platform and I had several reports about "devices becoming unresponsive after some time with MQTT" and I hope this will not increase problems.

**Comment by iprak** [comment]
> #define MQTT_PUBLISH_ITEM_VALUE_LENGTH 480 it's pretty lenghty, do we need that large values?
> 
> Aside from that, I think we will merge it soon and just see what happens. There are some rare edge cases on N platform and I had several reports about "devices becoming unresponsive after some time with MQTT" and I hope this will not increase problems.

Yes that was my concern from the very beginning which is why I went for dynamic allocation.

This is a discovery message sent from a switch based on ESPURNA which is 307. The device name matches the default device name in OBK.

The PWM devices would have this extra content `"on_cmd_type":"brightness","bri_scl":99,"bri_cmd_t":"ESPURNA-9DE8F9/0/set"` and the total becomes 381.

I perhaps reduce 480 a bit .. maybe 416 ?

**Comment by openshwprojects** [comment]
Ah, so it's related to discovery. Ok, maybe let's assume that this 480 bytes is OK for now. It's not that much as you think.

I wouldn't worry about that in this case, it can be 480 again.

Is there anything needed to be done before integrating this pull request?

**Comment by iprak** [comment]
I can't think of any other change for this merge, I have been tested this quite a bit with T and N devices and have seen no issues. I do log an error if the message value exceeds the limit; the code will not crash. Picking a smaller device name can work around the size limit in that case.

**Comment by openshwprojects** [comment]
If any issue with queuing arise, would it be possible to temporary change behaviour to "send immediately" with #define ? What is the motivation behind the queue addition?

**Comment by iprak** [comment]
The motivation was just to avoid any memory/crash issues for devices with multiple PWMs/switches since there we would be sending n MQTT messages. 

We never send out even the smaller MQTT status messages at once so I don't it feels right to send discovery messages immediately.

**Comment by iprak** [comment]
Any updates on this merge?

**Comment by openshwprojects** [comment]
I'm not sure, but let's give it a chance. I'll merge it now, but I hope you can provide support for that in the near future.

**Pull request merged**
