### PR TITLE
feat: automated GitHub releases

### PR DESCRIPTION
**Pull request by talltechdude**
Use GitHub actions to automatically build and release new versions, adding binaries to release outputs (e.g. https://github.com/talltechdude/OpenBK7231T_App/releases) and also tests builds on PRs.

Uses [Conventional Commits](https://www.conventionalcommits.org/) and [cycjimmy/semantic-release-action@v2](https://github.com/cycjimmy/semantic-release-action) to automatically increment release versions and generate change logs.

Also makes use of a simplified Makefile to build assets pulling in the SDK via a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to ease development of app only inside single repo (while remaining compatible with exisiting SDK)

### CODE REVIEW

**Comment by openshwprojects** [comment]
It seems very useful, but would it be possible to setup it for all three supported platforms, BK7231T, BK7231N and XR809?

**Comment by talltechdude** [comment]
Yep, no problems. I've got BK7231N compiling in Linux on GitHub but had to remove some `tuya_hal` references in wifi scan and flash read in order to get it to build (https://github.com/talltechdude/OpenBK7231T_App/blob/856da9f1bf1dac151c3363685a219ebbf202c895/src/httpserver/new_http.c)

**Comment by talltechdude** [comment]
Also having trouble compiling XR809 on linux with `Tiny_CRC8` missing currently from the `src` folder. Is that a library added recently? 
https://github.com/openshwprojects/OpenXR809/blob/9f99fbf2cb26a47abb3ce5154b7397b34263c187/project/oxr_sharedApp/gcc/Makefile#L37

**Comment by talltechdude** [comment]
Multi-platform concept does seem to be working though and I'll update the PR when I've ironed out some more of these issues (currently testing in https://github.com/talltechdude/OpenBK7231T_App/tree/feat/multi-platform-build)

**Comment by openshwprojects** [comment]
BK7231N and tuya_hal references - I fixed it yesterday. It was strange because for T version we had source code of tuya_Hal stuff, and in N version it was in Tuya.lib (precompiled only). I have removed/stubbed all functions and now both platforms compiles fine.

XR809 and Tiny_CRC8  - it was indeed a missing file, a mistake on my side as I am the only person doing whole XR809 work. Today I have ported buttons code to shared app so buttons are working on XR809. I also added missing CRC file.

Anyway, thanks for great input! I must look into the inner working on github builds, as I have never used them before.

**Comment by talltechdude** [comment]
Thanks for looking at that. I've now got it compiling successfully on all 3 platforms via GitHub actions (sample: https://github.com/talltechdude/OpenBK7231T_App/releases).

Needed to make some changes to the SDKs for BK7231N and XR809 so made some PRs for those. Once merged I'll update the submodules back to these upstream versions instead of my forks and mark this PR as ready for review.

**Comment by talltechdude** [comment]
@openshwprojects, are you able to merge the PRs for the [BK7231N](https://github.com/openshwprojects/OpenBK7231N/pull/1) and [XR809](https://github.com/openshwprojects/OpenXR809/pull/1) repos so I can finish off this PR? 

Thanks

**Comment by openshwprojects** [comment]
@talltechdude thanks for the great work! Sorry I somehow skipped it yesterday. I can merge right away, can you confirm that's ready now?

**Comment by openshwprojects** [comment]
Also, can you please include QIO file in release? At this point it seems that we need QIO for N version and UA for T version

**Comment by talltechdude** [comment]
@openshwprojects, this should be ready to merge now - exported the `QIO` file and switched to the merged upstream repos.

**Comment by openshwprojects** [comment]
Thanks! Let's see how this works in practise.

The mqtt_disconnect_my2 issue was just fixed by me. This fn was renamed at the first stages of the project because of conflict with Tuya lib, which is now excluded from build.

**Comment by openshwprojects** [comment]
Do I need to somehow manually refresh the repository links?
The automated build complains about "mqtt_disconnect" missing in T repo version, but I am sure I renamed back this function to mqtt_disconnect in T. https://imgur.com/a/kZSRQka

**Comment by talltechdude** [comment]
@openshwprojects, see PR #45 - I've added a makefile target to update the SDKs automatically and the builds are working as expected. The SDKs are pinned to a commit based on the submodule logic so will need to be updated for any upstream changes (i.e. run `make update-submodules`)

**Comment by openshwprojects** [comment]
@talltechdude any idea how to change the automated build system to use current commit hash name instead of 1.0.0 as SW_VERSION?
See:
https://github.com/openshwprojects/OpenBK7231T/commit/b7e9e6f04291db9af53bda0e8a3cb1ea6aaa5a0a

**Comment by talltechdude** [comment]
Yep, that's all customisable. Do you mean for the published versions? The GitHub actions will auto-increment the version numbers on pushes from commits matching the [Conventional Commits](https://www.conventionalcommits.org/) standards (e.g. my fork is at 1.0.7 by now https://github.com/talltechdude/OpenBK7231T_App/releases)

The PR builds etc already have branch name & commit hash in them:
https://github.com/openshwprojects/OpenBK7231T_App/blob/f6c3c8f68991c8f435a4528b33c521ccbb71eba9/.github/workflows/workflow.yaml#L44-L51

Local builds from my Makefile use the timestamp since commit hash is a hash and not actually forward incrementing.
https://github.com/openshwprojects/OpenBK7231T_App/blob/f6c3c8f68991c8f435a4528b33c521ccbb71eba9/Makefile#L13-L15

Up to you how you'd like all the different versions to increment, even [CalVer](https://calver.org/) is an option too whist the projects moving so fast

**Comment by openshwprojects** [comment]
@talltechdude  @iprak did W600 support, I have a fork here:
https://github.com/openshwprojects/OpenW600
Can you add this to automatic builds?

**Pull request merged**
