### PR TITLE
Hass / removed duplicate code

### PR DESCRIPTION
**Pull request by iprak**
* Consolidated duplicate strings/code, fixed some build warnings
* Added condiguration_url which appears here in HomeAssistant
image

### CODE REVIEW

**Comment by openshwprojects** [comment]
nice, is it really to roll?

**Comment by iprak** [comment]
yes

**Comment by openshwprojects** [comment]
Thanks. Ok so merging, altough I would just note, that I am not sure if doing #define for each string really helps - any modern compiler should already figure out constants and make them unique.

**Comment by iprak** [comment]
> Thanks. Ok so merging, altough I would just note, that I am not sure if doing #define for each string really helps - any modern compiler should already figure out constants and make them unique.

Thanks I was not completely sure about that.

**Pull request merged**
