### PR TITLE
Hass battery

### PR DESCRIPTION
**Pull request by Dheenhasty**
depend of  #682 

add auto discovery for battery on hass
add a flag to ignore the avty on sensor measurement for hass to keep value.

### CODE REVIEW

**Comment by openshwprojects** [comment]
It seems that all of your PRs include the same changes that were already merged in the past. For example:
image
I saw this in multiple PRs. Can you fix your further PRs so they only include new commits?
Thanks!

**Comment by Dheenhasty** [comment]
some sync issue. I will correct that, and update the branch.

**Comment by Dheenhasty** [comment]
close it to resolve sync issue

**Comment by openshwprojects** [comment]
okok

**Pull request closed without merging**
