### PR TITLE
Undelayedstart

### PR DESCRIPTION
**Pull request by btsimonh**
modify startup on beken to start some things early, and some things after TCP is ready,

### CODE REVIEW

**Comment by valeklubomir** [comment]
Last changes in Pins handler caused that Button/WifiLED no longer work.

**Comment by valeklubomir** [comment]
How this should work?

    uint32_t t_diff = g_last_time - g_time;
    // cope with wrap
   if (t_diff > 0x4000){
       t_diff = ((g_last_time + 0x4000) - (g_time + 0x4000));
    }

- "g_last_time - g_time" this gives always negative value, because g_last_time < g_time.
-  Logic behind 0x4000 is ??????

**Comment by btsimonh** [comment]
1/ uint32_t t_diff = g_last_time - g_time; should be uint32_t t_diff = g_time - g_last_time; - corrected now.

2/ if g_time has crossed the 32 bit boundary. t_diff will be large.  So if it is large, just push both times over the boundary and re-calc.  Not sure if is required with unsigned arithmatic?

**Comment by btsimonh** [comment]
button is still broken though :(.

**Comment by valeklubomir** [comment]
Crossing bounadary of 32-bit value take 1193 days.
But this will work correct.

    if (g_time < g_last_time)
    { 
        t_diff = 0xFFFFFFFFUL - g_last_time;   // ms till crossing
        t_diff += g_time;                                 // ms after crossing
    } else {
        t_diff = g_time - g_last_time;
    }

**Comment by btsimonh** [comment]
just pushed a fix for buttons.
@valeklubomir - check the last commit on main.  you will love the bug!!!!

**Comment by valeklubomir** [comment]
debounce_cnt is only 3-bit wide. new debounce_ms == 15 > 4 bit.

**Pull request merged**
