### PR TITLE
Start BL0937 driver for LN882H

### PR DESCRIPTION
**Pull request by giedriuslt**
Does not build due to missing driver functions, not sure why

### CODE REVIEW

**Comment by giedriuslt** [comment]
Changed to use normal interrupts instead of external ones (these are maybe to wake up from deep sleep, not sure), and a PR to enable building driver here https://github.com/openshwprojects/OpenLN882H/pull/5

**Comment by openshwprojects** [comment]
I have accepted the SDK PR but I am still unable to update submodules on main repo, can you try? It's strange, it worked for me many times before, am I  missing something?

**Comment by giedriuslt** [comment]
Did an update in my  branch, lets see if it works.

**Comment by giedriuslt** [comment]
Is there a guide how to build this locally?, It's messy to do it this way.
I added few more drivers in here https://github.com/openshwprojects/OpenLN882H/pull/7
It seems unexpectedly device groups driver is required too.

**Comment by openshwprojects** [comment]
it should not be required, maybe we're missing an #ifdef somewhere to disable device groups in certain setup?

**Comment by openshwprojects** [comment]
pwrCall is needed for power calibration, NTP also seems to be needed, it's for today-yesterday calculations

**Comment by openshwprojects** [comment]
https://github.com/openshwprojects/OpenLN882H/blob/master/english_lightningsemi_sdk_cross_build_setup.pdf

**Comment by giedriuslt** [comment]
well its a mess, it needs led drivers, then tyua mcu drivers, and now uart driver

**Pull request closed without merging**
