### PR TITLE
Adding Tasmota mecanism for Sensor

### PR DESCRIPTION
**Pull request by Dheenhasty**
Adding Tasmota Temp and Humidity for CHT8305 and SHT3X sensor.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Very nice, is it erady? There are compile errors

**Comment by Dheenhasty** [comment]
Yes regarding cross reference for non beken chip. I need to check why. I will try to find time today.

**Comment by openshwprojects** [comment]
you need to add #ifndef OBK_DISABLE_ALL_DRIVERS like:
image

**Comment by Dheenhasty** [comment]
Seems like OBK_DISABLE_ALL_DRIVERS work for BL0602 and W800 but not for the W600 ...... so try to force the platform dependent.

**Comment by Dheenhasty** [comment]
For future i will try to grab all the sdk to test compile before pushing
i done that for T and N ... but not the other

**Comment by Dheenhasty** [comment]
ready to merge :)

**Comment by openshwprojects** [comment]
Sorry, I was too busy, can you fix conflicts and I will merge it today or tomorrow?

**Comment by Dheenhasty** [comment]
No problem :) should be good

**Comment by openshwprojects** [comment]
Which order?
image

**Comment by Dheenhasty** [comment]
It's just a bad copy paste of the test_power comment....

Le mar. 7 mars 2023, 07:46, openshwprojects ***@***.***> a
écrit :

**Comment by openshwprojects** [comment]
Ok please fix it and I will merge, then we can start working on new things. I am making better docs now.

**Pull request merged**
