### PR TITLE
Public more device statuses via MQTT

### PR DESCRIPTION
**Pull request by iprak**
#104

This merge broadcasts the following values:
* host, mac, build: these are sent out once on startup
* datetime (if NTP driver is running), sockets, rssi, uptime, freeheap, ip: these get sent out every minute.

The values are similar to those broadcasted in Espurna. The ESP chip also provides internal voltage which is useful for battery based operations but I did not find any voltage level in the sdk.

Both sets of values are enabled by the `OBK_FLAG_MQTT_BROADCASTSELFSTATEPERMINUTE` flag.

I also fixed a few unused compile warnings due to unused variables.

### CODE REVIEW

**Comment by openshwprojects** [comment]
This is very good job, but I request one change: you can't use bk_wlan_get_link_status directly because it breaks compilation on other platforms. 
Do you know how to make bk_wlan_get_link_status multiplatform? If not, ask me, I will give some explanation

Something like HAL_Get_RSSI and put it on all device-specific wifi files (with placeholders for other devices)

**Comment by iprak** [comment]
I just realized the same when the push jobs failed and created a HAL_ function to handle other devices. I committed my changes but I still see many build failures on XR809 even on master branch (without my changes).

**Comment by openshwprojects** [comment]
@iprak  don't worry about XR809, it's my fault, I will update XR809 support later.

Is BL602 and W800 compiling now?

**Comment by iprak** [comment]
No they both are failing too with similar error. I have not been able to build W800 locally but I am going to try BL602 next. This is from the W800 error log.

```
CC  
./bin/build/w800/lib/libuser.a(new_mqtt.o): In function `$t':
(.text.MQTT_DoItemPublish+0x1a): undefined reference to `DRV_IsRunning'
./bin/build/w800/lib/libuser.a(new_mqtt.o): In function `$t':
(.text.MQTT_DoItemPublish+0x1a): relocation truncated to fit: R_CKCORE_PCREL_IMM26BY2 against undefined symbol `DRV_IsRunning'
./bin/build/w800/lib/libuser.a(new_mqtt.o): In function `$t':
(.text.MQTT_DoItemPublish+0x12c): undefined reference to `NTP_GetCurrentTime'
./bin/build/w800/lib/libuser.a(new_mqtt.o): In function `$t':
(.text.MQTT_DoItemPublish+0x12c): relocation truncated to fit: R_CKCORE_PCREL_IMM26BY2 against undefined symbol `NTP_GetCurrentTime'
collect2: error: ld returned 1 exit status
make[1]: *** [tools/w800/rules.mk:169: bin/build/w800/image/w800.elf] Error 1
make: *** [Makefile:111: OpenW800] Error 2
make[1]: Leaving directory '/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenW800'
Error: Process completed with exit code 2.
```

I had included these in new_mqtt.c for those 2 functions.
```
#include "../driver/drv_public.h"
#include "../driver/drv_ntp.h"
```

**Comment by openshwprojects** [comment]
Ok, maybe I will just fix them myself? 

It seems that simply NTP driver was not included in those builds, I would guess.

**Comment by iprak** [comment]
Ok now I understand the build a little more. This error seems to be because  `OpenW800\app\Makefile` does not include any files from driver folder and maybe something like that is happening for BL602 as well.

I added this locally

```
CSRCS += $(_SHARED_APP)/driver/drv_ntp.c
CSRCS += $(_SHARED_APP)/driver/drv_main.c
```

which resulted in these new errors; these functions are invoked from `drv_main.c`.
```
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x4): undefined reference to `TuyaMCU_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x8): undefined reference to `TuyaMCU_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x44): undefined reference to `DRV_I2C_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x48): undefined reference to `DRV_I2C_EverySecond'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x64): undefined reference to `BL0942_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x68): undefined reference to `BL0942_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x6c): undefined reference to `BL09XX_AppendInformationToHTTPIndexPage'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x84): undefined reference to `BL0937_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x88): undefined reference to `BL0937_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0x8c): undefined reference to `BL09XX_AppendInformationToHTTPIndexPage'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xa4): undefined reference to `CSE7766_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xa8): undefined reference to `CSE7766_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xac): undefined reference to `BL09XX_AppendInformationToHTTPIndexPage'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xc4): undefined reference to `SM2135_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xc8): undefined reference to `SM2135_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xd8): undefined reference to `SM2135_OnChannelChanged'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xe4): undefined reference to `BP5758D_Init'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xe8): undefined reference to `BP5758D_RunFrame'
./bin/build/w800/lib/libuser.a(drv_main.o):(.data.g_drivers+0xf8): undefined reference to `BP5758D_OnChannelChanged'
```

It feels that maybe the driver framework is not ready for other chips and I should restrict the NTP feature till then .. maybe based on `PLATFORM_BEKEN`? 

But I saw `PLATFORM_BEKEN` used around which sort of suggests that maybe it is for something else.

#if PLATFORM_BEKEN
	{ "DGR", DRV_DGR_Init, NULL, NULL, DRV_DGR_RunFrame, DRV_DGR_Shutdown, DRV_DGR_OnChannelChanged, false },
#endif

**Comment by iprak** [comment]
So I went ahead and locally added all driver files which then gave failures in drv_bl0937.cs which has these BK7231 framework specific references.

```
#include "BkDriverTimer.h"
#include "BkDriverGpio.h"
#include "sys_timer.h"
#include "gw_intf.h"
```

I don't think the drivers in current state can be built for other chips.

**Comment by openshwprojects** [comment]
There is a better solution for that - there is a #define OBK_DISABLE_ALL_DRIVERS , you can search for this in app code.

Drivers are not build on, for example, XR809 because I have never found an XR809 device requiring them.

**Comment by iprak** [comment]
I have adjusted the build for OpenXR809 separately (https://github.com/openshwprojects/OpenXR809/pull/2) , that along with the last set of changes should fix all build errors for XR809.

**Comment by openshwprojects** [comment]
XR809 pull requested merged, is this pull requested for App ready as well?

Thanks!

**Comment by iprak** [comment]
I had added `SRCS += ../shared/src/cmnds/cmd_tcp` to `OpenXR809/tree/master/project/oxr_sharedApp/gcc` but the build failure log does not contain `cmnds\cmd-tcp` in the SRCS list. I had also added `shared/src/rgb2hsv` and `shared/src/hal/xr809/hal_adc_xr809` and these too don't appear in the list. 

`
SRCS is ../main ../serial ../my_lwip2_mqtt_replacement ../../../project/common/cmd/cmd_ce ../../../project/common/cmd/cmd_sd ../../../project/common/cmd/cmd_sntp ../../../project/common/cmd/cmd_airkiss ../../../project/common/cmd/cmd_sysinfo ../../../project/common/cmd/cmd_rtc ../../../project/common/cmd/cmd_i2c ../../../project/common/cmd/cmd_audio ../../../project/common/cmd/cmd_mqtt ../../../project/common/cmd/cmd_timer ../../../project/common/cmd/cmd_flash ../../../project/common/cmd/cmd_broadcast ../../../project/common/cmd/cmd_upgrade ../../../project/common/cmd/cmd_echo ../../../project/common/cmd/cmd_pm ../../../project/common/cmd/cmd_auddbg ../../../project/common/cmd/cmd_wlan ../../../project/common/cmd/cmd_fs ../../../project/common/cmd/cmd_adc ../../../project/common/cmd/cmd_thread ../../../project/common/cmd/cmd_gpio ../../../project/common/cmd/cmd_etf ../../../project/common/cmd/cmd_pwm ../../../project/common/cmd/cmd_util ../../../project/common/cmd/cmd_ota ../../../project/common/cmd/cmd_smartlink ../../../project/common/cmd/cmd_httpd ../../../project/common/cmd/cmd_irtx ../../../project/common/cmd/cmd_nopoll ../../../project/common/cmd/cmd_heap ../../../project/common/cmd/cmd_arp ../../../project/common/cmd/cmd_smart_config ../../../project/common/cmd/cmd_wdg ../../../project/common/cmd/cmd_ping ../../../project/common/cmd/cmd_mem ../../../project/common/cmd/cmd_dhcpd ../../../project/common/cmd/cmd_efpg ../../../project/common/cmd/cmd_netcmd ../../../project/common/cmd/cmd_iperf ../../../project/common/cmd/cmd_clock ../../../project/common/cmd/cmd_uart ../../../project/common/cmd/cmd_irrx ../../../project/common/cmd/cmd_ifconfig ../../../project/common/cmd/cmd_voice_print ../../../project/common/cmd/cmd_httpc ../../../project/common/cmd/cmd_cedarx ../../../project/common/cmd/tls/cmd_tls ../../../project/common/cmd/tls/client ../../../project/common/cmd/tls/tls ../../../project/common/cmd/tls/server ../../../project/common/cmd/tls/custom_certs ../../../project/common/startup/gcc/retarget ../../../project/common/startup/gcc/retarget_main ../../../project/common/startup/gcc/exception ../../../project/common/startup/gcc/retarget_stdout ../../../project/common/startup/gcc/startup ../../../project/common/iperf/iperf ../../../project/common/apps/buttons/buttons ../../../project/common/apps/buttons/buttons_low_level ../../../project/common/framework/fs_ctrl ../../../project/common/framework/net_ctrl ../../../project/common/framework/sc_assistant_port ../../../project/common/framework/audio_ctrl ../../../project/common/framework/net_sys ../../../project/common/framework/sysinfo ../../../project/common/framework/platform_init ../../../project/common/framework/sys_ctrl/event_queue ../../../project/common/framework/sys_ctrl/container ../../../project/common/framework/sys_ctrl/observer ../../../project/common/framework/sys_ctrl/looper ../../../project/common/framework/sys_ctrl/sys_ctrl ../../../project/common/framework/sys_ctrl/publisher ../../../project/common/board/board ../../../project/common/board/board_common ../../../project/common/board/xr809_module/board_config ../shared/src/new_cfg ../shared/src/new_pins ../shared/src/new_common ../shared/src/new_builtin_devices ../shared/src/httpserver/new_http ../shared/src/httpserver/http_tcp_server ../shared/src/httpserver/http_fns ../shared/src/httpserver/rest_interface ../shared/src/logging/logging ../shared/src/jsmn/jsmn ../shared/src/mqtt/new_mqtt ../shared/src/tiny_crc8 ../shared/src/new_ping ../shared/src/cmnds/cmd_main ../shared/src/cmnds/cmd_newLEDDriver ../shared/src/cmnds/cmd_repeatingEvents ../shared/src/cmnds/cmd_tasmota ../shared/src/cmnds/cmd_test ../shared/src/cmnds/cmd_tokenizer ../shared/src/cmnds/cmd_eventHandlers ../shared/src/cmnds/cmd_channels ../shared/src/driver/drv_bl0942 ../shared/src/driver/drv_main ../shared/src/driver/drv_ntp ../shared/src/driver/drv_tuyaMCU ../shared/src/driver/drv_uart ../shared/src/i2c/drv_i2c_main ../shared/src/i2c/drv_i2c_mcp23017 ../shared/src/i2c/drv_i2c_tc74 ../shared/src/i2c/drv_i2c_lcd_pcf8574t ../shared/src/hal/xr809/hal_wifi_xr809 ../shared/src/hal/xr809/hal_generic_xr809 ../shared/src/hal/xr809/hal_main_xr809 ../shared/src/hal/xr809/hal_pins_xr809 ../shared/src/hal/xr809/hal_flashConfig_xr809 ../shared/src/hal/xr809/hal_flashVars_xr809 ../shared/src/user_main
`

It seems that older OpenXR809 is being pulled for build and the Source checkout step of the workflow confirms this. The hash `99f095f70105a049bcd30cb55d1874af800c4a02` represents code from 5/16/2022. Does something else need to be done to pull in latest version?

```
From https://github.com/openshwprojects/OpenXR809
   * branch            99f095f70105a049bcd30cb55d1874af800c4a02 -> FETCH_HEAD
  Submodule path 'sdk/OpenXR809': checked out '99f095f70105a049bcd30cb55d1874af800c4a02'
  /usr/bin/git submodule foreach --recursive git config --local gc.auto 0
```

**Comment by openshwprojects** [comment]
I haven't this issue before. Maybe you need to start a fresh new build.

Still, what about it: I will accept the pull request now, and we (or I) will solve XR809 issue later?

Is everything else (except XR809) ready?

**Comment by iprak** [comment]
Yes everything else is ready.

I did synch my fork+branch and then resubmitted a white space commit to trigger the workflow checks.

**Comment by iprak** [comment]
I think is because the submodule attached to the repo is at older state (May 16):
image

I ran into the same error for another PR. So I updated the  submodule OpenXR809 and then pushed it which moved up the submodule reference.
image

This submodule stuff is new to me.

**Comment by openshwprojects** [comment]
Great, thank you for great input!

**Comment by openshwprojects** [comment]
I merged it for now, but I will also test it a bit tomorrow, especially because there is an edge case where doing lots of MQTT publish can overload the device (but since you are using my round robin publish api, everything should be ok)

**Pull request merged**
