### PR TITLE
fixes for bugs from #810

### PR DESCRIPTION
**Pull request by serek4**
fixes for bugs from [this comment](https://github.com/openshwprojects/OpenBK7231T_App/issues/810#issuecomment-1525941122)
- fixed tasmota tele/sensor sent additionally with tele/status
- ~~fixed tasmota topics sent with mqtt_broadcastInterval when flag 2 is enabled~~

plus
- tasmota topics sent on mqtt connect only when flag 10 is enabled
- fixed tasmota tele publish +1s from set interval

### CODE REVIEW

**Comment by serek4** [comment]
No, it were not intendent.
That line was removed to not send tasmota topics with mqtt_broadcastInterval when flag 2 is enabled.
I will fix that.

**Comment by serek4** [comment]
reverted b40665ae336a9b5fa5829b34b1a41acc28b69cfb, so everything should work as before

**Comment by openshwprojects** [comment]
Seems okay now to me. So, what do you say, should I merge it already?

**Comment by serek4** [comment]
Yes. I'm ok with changes as well.

**Pull request merged**
