### PR TITLE
HomeAssistant / Discovery / Add sensor units

### PR DESCRIPTION
**Pull request by iprak**
* Added separate const for mqtt sensor class and units.
* Added missing units for voltage, current and power.
* Also added Wh unit for energy when device_class is not None.

https://github.com/openshwprojects/OpenBK7231T_App/issues/322

### CODE REVIEW

**Comment by iprak** [comment]
@openshwprojects new_mqtt_deduper.c is causing build failures

```
../shared/src/user_main.o: In function `Main_OnEverySecond':
/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenXR809/project/oxr_sharedApp/gcc/../shared/src/user_main.c:204: undefined reference to `MQTT_Dedup_Tick'
collect2: error: ld returned 1 exit status
make[2]: *** [../../../project/project.mk:204: oxr_sharedApp.axf] Error 1
make[2]: Leaving directory '/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenXR809/project/oxr_sharedApp/gcc'
make[1]: Leaving directory '/home/runner/work/OpenBK7231T_App/OpenBK7231T_App'
make[1]: *** [Makefile:95: build-XR809] Error 2
make: *** [Makefile:90: OpenXR809] Error 2
Error: Process completed with exit code 2.
```

```
./bin/build/w800/lib/libuser.a(cmd_newLEDDriver.o): In function `sendColorChange.part.1':
(.text.sendColorChange.part.1+0x50): undefined reference to `MQTT_PublishMain_StringString_DeDuped'
./bin/build/w800/lib/libuser.a(cmd_newLEDDriver.o): In function `sendColorChange.part.1':
(.text.sendColorChange.part.1+0x50): relocation truncated to fit: R_CKCORE_PCREL_IMM26BY2 against undefined symbol `MQTT_PublishMain_StringString_DeDuped'
collect2: error: ld returned 1 exit status
make[1]: *** [tools/w800/rules.mk:169: bin/build/w800/image/w800.elf] Error 1
make[1]: Leaving directory '/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenW800'
make: *** [Makefile:121: OpenW800] Error 2
Error: Process completed with exit code 2.
```

**Comment by openshwprojects** [comment]
@iprak  just missing from makefile on those platforms, I will fix it tomorrow, or you can do it earlier.

**Comment by iprak** [comment]
https://github.com/openshwprojects/OpenW600/pull/1

https://github.com/openshwprojects/OpenXR809/pull/5

**Comment by openshwprojects** [comment]
Thank you! I just woke up and started working on OBK. Your support is very valuable. I am releasing the online devices list, see main readme on our main page for details.

Merging this now.

**Pull request merged**
