### PR TITLE
added linear mapping function to map 0-255 to 0-1023

### PR DESCRIPTION
**Pull request by Refuhr**
I noticed that the 8 to 10 bit conversion is just a simple multiplication by 4. 
```c
cur_col_10[i] = rgbcw[g_channelOrder[i]] * 4;
```
I now added a simple linear mapping function to improve the 8 to 10 bit mapping:
```c
// Arduino mapping function
cur_col_10[i] = (rgbcw[g_channelOrder[i]] - 0x00) * (0x3FF - 0x00) / (0xFF - 0x00) + 0x00;
```

### CODE REVIEW

**Comment by openshwprojects** [comment]
May I know what it exactly changes?

**Comment by Refuhr** [comment]
Essentially it just changes the factor from 4 to (1023/255) and makes it so that you get the full output range. I could put it in header or just write (1023/255).

**Comment by openshwprojects** [comment]
maybe better make it project-wide and put in new_common?

**Comment by Refuhr** [comment]
I put it in new_common.h and tested it.

**Comment by openshwprojects** [comment]
Thanks!

**Pull request merged**
