### PR TITLE
New features for Smart plugs (BK7231N+BL0937). MQTT upgrades.

### PR DESCRIPTION
**Pull request by valeklubomir**
Device: TESLA Smart Plug.
Model: TSL-SPL-1
Description: BK7231N chipset. BL0937 energy monitor. 1x RELAY, 1x Button, 1xLED

- MQTT - Connect handling modifications, stats generation.
- MQTT - Front page MQTT stas added.
- BL0937 implemented experimantal energy meter

### CODE REVIEW

**Comment by openshwprojects** [comment]
XR809 and BL602 does not build. Can you fix it, or do I have to resolve it myself? Most likely just need a #ifdef PLATFORM_XR809...

**Comment by valeklubomir** [comment]
I will try to fix XR809 and BL602 builds.

**Comment by openshwprojects** [comment]
I have managed to gather some N devices, mostly bulbs. I didn't have much problems with them in the past because they were powered off and on frequently, but I made a test bench that will keep them running forever. I will flash them now with your changes (after merging pull request) and we will see how they work.

**Comment by openshwprojects** [comment]
/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenBL602/customer_app/bl602_sharedApp/bl602_sharedApp/shared/src/mqtt/new_mqtt.c: In function 'MQTT_RunEverySecondUpdate':
/home/runner/work/OpenBK7231T_App/OpenBK7231T_App/sdk/OpenBL602/customer_app/bl602_sharedApp/bl602_sharedApp/shared/src/mqtt/new_mqtt.c:1038:49: error: invalid application of 'sizeof' to incomplete type 'mqtt_client_t' {aka 'struct mqtt_client_s'}
                 mqtt_client_cleanup(mqtt_client);

**Comment by valeklubomir** [comment]
At moment I have issues with building OpenBL602. Working on it. It is slow process. I need patience.

**Comment by valeklubomir** [comment]
When running make, I get following message:

fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'sdk/OpenW800'
Makefile:34: recipe for target 'submodules' failed
make[1]: *** [submodules] Error 1
make[1]: Leaving directory '/root/BK7231N/OpenBK7231T_App'
Makefile:69: recipe for target 'OpenBK7231T' failed
make: *** [OpenBK7231T] Error 2

Any Idea?

**Comment by openshwprojects** [comment]
Maybe this can help?
https://stackoverflow.com/questions/40987847/unable-to-find-current-origin-master-revision-in-submodule-path

**Comment by openshwprojects** [comment]
maybe just do memset(cl,0,sizeof(*cl)) ?

**Comment by valeklubomir** [comment]
New simpler solution commited.

**Comment by valeklubomir** [comment]
In the moment I can run build only for OpenBK7231N and T.

**Comment by openshwprojects** [comment]
I think that pull requests will run automatically compilation of your changes after I accept your first pull request here.

**Pull request merged**
