### PR TITLE
Home Assistant discovery - add energy counters today/yesterday, add clear date, add friendly names

### PR DESCRIPTION
**Pull request by stefan064**
Hi openshwprojects,
I'd like to offer mycontribution for energy monitoring devices.
Reason for changes:
- #805 - Energy counters for today/yesterday and energy clear date are not being discovered by home assistant

Cause of reason:
- The missing entities are not included in home assistant mqtt discovery topics

Changes made:
- Added missing items to home assistant discovery generation
- Added friendly names to the home assistant entities. e.g. energycounter_today displays as 'Energy Today'
- Added 'Energy Clear Date (i.e. energycounter_clear_date)'
- Changed formatting of 'energycounter_clear_date' so home assistant can use it as a timestamp instead of a string.

Before:
Screenshot 2024-02-18 103845
After:
Screenshot 2024-02-18 112921
Thankyou for this great project.

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thank you, it seems like a great addition. Just to be sure, is this "combo name" here correct? When is it used?
image

**Comment by TurkeyMan** [comment]
Hi there, while at it, can add reporting for apparentpower, reactivepower, and powerfactor?

**Comment by stefan064** [comment]
"Voltage or Current or Power" is the fall-back home assistant entity name in case the name can't be retrieved from `sensor_hassNames[]` (previously `sensor_mqttNames[]`). I saw and changed this while debugging only after finding the previous string "Power" a bit confusing because a `VCP_SENSOR` can also be a voltage or current. I don't think this string is meant to be seen in normal usage.

**Comment by openshwprojects** [comment]
Can you fix W800 so I can mergei t?

**Comment by stefan064** [comment]
I'm a bit held up on OpenW800 failing the checks here;
```
CC  
./bin/build/w800/lib/libuser.a(hass.o): In function `$d':
(.text.hass_init_device_info+0x2a0): undefined reference to `sensor_hassNames'
```
Something linking related specific to that build? Would appreciate a second opinion if anyone has some clues.

**Comment by stefan064** [comment]
Some progress with adding power factor, reactive power, apparent power here:
[](https://github.com/stefan064/OpenBK7231T_App/tree/refactor-energy-sensors)
Testing this so far. Keen on feedback about how much home assistant reconfiguring it may or may not impose on existing setups.
image

**Comment by openshwprojects** [comment]
Very nice, it seems that all compile errors are fixed. Do you think it's ready for merge?

**Comment by stefan064** [comment]
Yes please it's good to go, no issues in my testing so far. I'll make a separate PR for the other additions.

**Comment by TurkeyMan** [comment]
That's super awesome, thanks for doing this!

There's one odd thing to note in your screenshot though; not sure if a bug or a hardware thing... did you notice that Apparent power is ~200VA, and Power is ~260W... how did we get there?
Power factor says 0.67. Something's wrong...?

**Comment by TurkeyMan** [comment]
It says above "This PR is included in version 1.17.478", I just updated to test this out, but it doesn't seem to be reporting any of those additional energy values. I'm still only getting reports for `voltage`, `power`, `current`.
Is it behind a new option or anything?

**Comment by TurkeyMan** [comment]
Also I was thinking on the report options `VCPPrecision` `VCPPublishThreshold` for those values.
I reckon apparent power and reactive power can follow the same precision and threshold as power, but powerfactor might need values specified from those 2 options.

**Comment by stefan064** [comment]
Home assistant discovery may need retriggering to make the new values appear, e.g. via web ui `Config -> home assistant configuration -> start home assistant discovery`, or via command scheduleHADiscovery. Not sure why thats been necessary but may relate to how home assistant interprets the order of things. I also saw that
- deleting the device from HA also deletes its discovery topics from mqtt. 
- manally deleting retained discovery topics causes HA to remove their sensors automatically
- Deleting from HA then re-adding via 'scheduleHADiscovery' brings the device back including entity history when entity ids match. HA generates entity id from device name and sensor names.
Thankyou @TurkeyMan for spotting that, they probably were wrong too as I later learnt about how hass `uniq_id` works...
I'll share further progress via your #1097

**Comment by TurkeyMan** [comment]
When I click "start home assistant discovery", it just shows a message "MQTT not running".
What is this actually supposed to do?
I'm not using homeassistant... what is the goal here, or what mechanism will make it start reporting these new topics?

**Pull request merged**
