### PR TITLE
Adding SHT3X Driver

### PR DESCRIPTION
**Pull request by Dheenhasty**

### CODE REVIEW

**Comment by Dheenhasty** [comment]
to resolve #574 Adding SHT3X driver support maybe not so clean and could be a lot better

**Comment by openshwprojects** [comment]
It seems great for a start, but depending on your coding skills, I'd suggest a few changes for a future.

1. if the I2C code is the same here and in previous CHT driver, and also in my Soft I2C driver, I'd consider merging that in the future
2. We are usually trying to avoid setting channel types where user can't see it 
image
is it required for you?

**Comment by Dheenhasty** [comment]
Yes i have done that as a quick and dirty, but ideally a regroupement of SOFT I2C, CHT and SHT will be good. 

i will try to do that, but my coding skill might not help. 

for the channel set no it's was just to force the readability on web interface. but it can be removed and set at script level

**Comment by openshwprojects** [comment]
@Dheenhasty ok I will merge it now and I will do I2C optimization later, ok?

**Comment by Dheenhasty** [comment]
perfect, i will have some time to work on it this week end. but i will do another merge. 

Want to check the mqtt discovery for sensor too (could really help here)

**Comment by openshwprojects** [comment]
@Dheenhasty DHTs are already discovered so discovery should be very easy

**Pull request merged**
