### PR TITLE
Allow BridgePulseLength to set to lower values

### PR DESCRIPTION
**Pull request by ataa**
- To add support for ZMAi-90 Smart Switch (with CBU Module) Bi-Stable relay.
Tested on ZMAi-90 with BridgePulseLength set to 5.
- Fix some typos

### CODE REVIEW

**Comment by openshwprojects** [comment]
Seems good, but any reason why pulse widht must be lower?

**Comment by ataa** [comment]
​​
On my ZMAi-90 (CBU), Using the default value of 50, The relay remains energized for much longer than necessary and it makes a static noise for a second or two after open/close. Setting the Pulse Length to 5 fixes this issue. 
<sup>Not sure if I am using the correct technical terms in English.</sup>

**Comment by openshwprojects** [comment]
that could be interesting, if you want, you can post a video and a few words about this device/setup/change/fix on our forum:
https://www.elektroda.com/rtvforum/forum390.html
i will merge it tomorrow

**Comment by ataa** [comment]
There's a post about this device and the relay issue: https://www.elektroda.com/rtvforum/topic3928655.html

**Pull request merged**
