### PR TITLE
Driver for BMP085, 180, 280, and BME280, 680, 688.

### PR DESCRIPTION
**Pull request by NonPIayerCharacter**
BMP280 and BME680 works, unsure for BMP180. Mine prints nonsensical readings, and i don't have a free esp board to test it for now.
Don't have the others, but BME688 is the same as BME680, as is BMP085 and BMP180. BME280 will work with pressure and temperature, but humidity is yet to be tested.
This driver additionally have configuration (oversampling, iir filter, etc.), cycle setting and calibration.
Chose not to implement gas readings and heater on BME68X, but, if needed, can be added later.

### CODE REVIEW

**Comment by NonPIayerCharacter** [comment]
image

**Comment by openshwprojects** [comment]
Thank you! Very good, is it ready to merge? 

For me it looks ready to merge, the only thing I will change is that I will disable it by default (to reduce flash size...)

**Comment by divadiow** [comment]
great work 

image

`startdriver bmpi2c 11 10 1 2 3 0` for me

image

Flash ID detected gone though :(

https://github.com/openshwprojects/OpenBK7231T_App/pull/1230/files#diff-c09607b072ad165703176006f86dda08091db37f2fc08c49620769f696734261

image

**Comment by NonPIayerCharacter** [comment]
Chip id is not logged, if it is one of the known ones. If unknown, it will still be printed.

**Comment by divadiow** [comment]
cool

**Comment by divadiow** [comment]
I was not concentrating and connected VCC to SDL or SDA and killed my BME280 🙄. new one arriving in a day or so.

**Comment by NonPIayerCharacter** [comment]
Verified that my bmp180 works ok with esp. Still unable to make it work on beken, even tried to make a new library from scratch for it. Will try to debug it later, with first comparing calibration data readings.

**Comment by openshwprojects** [comment]
Ok what is the state of this? Maybe I can merge it already (as disabled) and we will patch it later?

Futhermore, does your @NonPIayerCharacter previous PR also requires a merge or is everything inside that current PR?

**Comment by NonPIayerCharacter** [comment]
Everything, save bmp180 is done. It can be merged, will open a new pull if i will be able to solve the problem with it. Previous pull is for bmp280 driver, therefore a separate one, and should be tested with bme280 before merge.

**Comment by divadiow** [comment]
sorry for the wait. new BME280 still not arrived.

**Comment by openshwprojects** [comment]
So I will merge that one now. Thank you!

**Review by openshwprojects — APPROVED** [review]

**Pull request merged**
