### PR TITLE
Attempt to make power monitoring work with a BL602+BL0937 combo

### PR DESCRIPTION
**Pull request by sverd**
The building did not start automagically, probably because of something I did or did not do...... But as suggested in  [the elektroda page](https://www.elektroda.com/rtvforum/topic3945009.html#20618437) I created this pull request.... hopefully this helps...

### CODE REVIEW

**Comment by sisalik** [comment]
I see the BL602 build failed, but did it end up producing a working binary at all or did you find another solution to your issue @sverd? I've got the same device as you, dealing with the same problems.

**Comment by hojnikb** [comment]
Any news on this combo? I have the same device.

**Comment by sisalik** [comment]
Not from me, I'm afraid... I had a go in [my fork](https://github.com/sisalik/OpenBK7231T_App/tree/feature/add_bl0937_support_to_bl602_platform) and got it to build but the device kept freezing after boot and I accidentally blew it up while debugging, so it might be a while until I can try again haha.

**Comment by iRia58** [comment]
@sisalik hello i have two with combo bl602 bl0937 smart plug i can test for you but i'm novice. do you have discord for chat

**Comment by openshwprojects** [comment]
Solved in this topic:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20919936#20919936
@iRia58 @sisalik @hojnikb @sverd

**Pull request closed without merging**
