### PR TITLE
Ssid2modv2

### PR DESCRIPTION
**Pull request by xjikka**
Updated ssid2mod as discused here 
https://github.com/openshwprojects/OpenBK7231T_App/pull/1254

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thanks, can anyone give some final testing to this PR? @divadiow ? @DeDaMrAzR  ?

**Comment by divadiow** [comment]
seems OK. Tested on T and N. set OBK1 and OBK2 test SSIDs in web config. disabled OBK1 and ~4 mins later both connected to OBK2. Disabled OBK2 and re-enabled OBK1 and both connected again after 4 mins

image

**Comment by divadiow** [comment]
and warning text on non-Bk 

image

**Comment by divadiow** [comment]
Is this complete now for BK?

**Comment by rafalolb** [comment]
What is a problem to merge to master? We waiting to @openshwprojects approve?

**Comment by xjikka** [comment]
@rafalolb I don't know...

**Comment by rafalolb** [comment]
@divadiow, @openshwprojects Could you approve this branch to master?

**Comment by Kobbe1** [comment]
Can someone share the binary of this pull please? I used it and it worked, but seems I did not save it. It is no longer available on github it seems so till it is merged would like to use that ...

**Comment by divadiow** [comment]
[OpenBK7231T_App_1274_merge_85f9bfa248e7.zip](https://github.com/user-attachments/files/17406615/OpenBK7231T_App_1274_merge_85f9bfa248e7.zip)

**Comment by divadiow** [comment]
> @divadiow, @openshwprojects Could you approve this branch to master?

I cannot do this. I am a regular user.

**Comment by xjikka** [comment]
Here is the recompiled version 1.17.748, but I don't have a chance to try it right now. There are some changes in connect to WiFi timing that could affect this. If you want, try it and give info if OK.
[BK7231N-1.17.748-ssid2.zip](https://github.com/user-attachments/files/17408009/BK7231N-1.17.748-ssid2.zip)
[BK7231T-1.17.748-ssid2.zip](https://github.com/user-attachments/files/17408011/BK7231T-1.17.748-ssid2.zip)

**Comment by rafalolb** [comment]
@xjikka Can you merge master/original to your branchSsid2Mode2?

**Comment by openshwprojects** [comment]
I've merged main and I can merge it PR , but can someone do few more tests to confirm it's working correctly?

**Comment by xjikka** [comment]
@openshwprojects I added changes to the main for test /zip/ and tested on the BK7231T. 
SSID switching works correctly:
- connection to SSID1 after power-on 0:10 +/-
- connection to SSID2 after power-on 3:45 +/-
- SSID switching takes +/- 4:45.

But, there is one problem with SSID2 editing - regardless of SSID2 functionality. Once SSID2 is entered, it cannot be deleted. If it is set as empty in the web admin, it will still come back after saving and reload.
Reset using the command is also not possible, the SSID2 command does not exist.
This will probably be easier and quicker to fix for someone who knows the config editing code in the webadmin in OpenBKT.

[ssid2.zip](https://github.com/user-attachments/files/17421874/ssid2.zip)

**Comment by xjikka** [comment]
I've updated https://github.com/xjikka/OpenBK7231T_App/tree/ssid2modv2 to main + 2 changed files
src\httpserver\http_fns.c
src\user_main.c

**Comment by Kobbe1** [comment]
fyi, I did some tests with 4 smart sockets and above binaries. Things worked pretty well, switching from one weak network to another stronger did work most of the time too, took quite a while. No stability issues

**Comment by openshwprojects** [comment]
Ok, I will merge it now and I will address the HTTP page issue next.

**Pull request merged**
