### PR TITLE
Improve flags config html

### PR DESCRIPTION
**Pull request by iprak**
This request 
* Aligns the layout of checkbox (before the label and not underneath it)
* Makes the checkbox more accessible (label can be clicked to change the state)

Before:
image

New layout:
image

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thanks, by the way, there is one change we need... we need to move the link for the javascript panel which is now "hidden" under options (a small URL under buttons) to the main page, to the button. Create a button with that link on the main page under "Options" so it's clearily visible. Would you like to do that?

**Comment by iprak** [comment]
> Thanks, by the way, there is one change we need... we need to move the link for the javascript panel which is now "hidden" under options (a small URL under buttons) to the main page, to the button. Create a button with that link on the main page under "Options" so it's clearily visible. Would you like to do that?

I can do that but I am not following what you are referring to.

**Comment by pretoriano80** [comment]
@iprak i think he mean to have a button to open the WebApp just like the other options (eg. the Quick Config button ).
At the moment there's just a small link/hyperlink at the bottom of the WebUI ,which is easy to miss .
And probably it's best to have it on the WebUI main page .

**Comment by iprak** [comment]
I will let @openshwprojects confirm if that is what he requested. I agree that having `[Launch Web Application` on the main page would be more useful.

**Comment by openshwprojects** [comment]
I think you are correct. My suggestion was to remove this:
image
and add here (with a better Title, better color, etc):
image

**Review by openshwprojects — APPROVED** [review]

**Pull request merged**
