### PR TITLE
Update cmd_main.c - powersave description update

### PR DESCRIPTION
**Pull request by divadiow**
https://github.com/openshwprojects/OpenBK7231T_App/pull/1186

### CODE REVIEW

**Review by openshwprojects — APPROVED** [review]

**Comment by MaxineMuster** [comment]
Hi,

iirc, for LN882H it was "ln_pm_sleep_mode_set(LIGHT_SLEEP)" which rendered results from BL0937 unusable.
So we introduced "PowerSave 2" to set this mode, leaving `PowerSave 1`  to work with  BL0937 present.

So, if I'm not mistaken, the text should be:

On LN882H PowerSave >1 (eg `PowerSave 2`) should **not** be used if BL0937 metering is present.

Or: 

On LN882H only `PowerSave 1` should be used if BL0937 metering is present.

Regards

**Comment by divadiow** [comment]
right OK. I was reading it the other way round.

so on LN `powersave 1` is a deeper sleep than `powersave >1`?

and the lighter sleep makes BL0937 unusable whereas the deeper sleep is fine with BL0937?

**Comment by MaxineMuster** [comment]
Nope.

1 is "lighter" sleep (and doesn't seem to impact pulse counting)
2 is "deeper" sleep (and pulse counting is not working correct)

So, you should not use >1 if you want a correct reading.

**Comment by divadiow** [comment]
lol. that makes more sense. I'll do PR to fix. ta

**Comment by MaxineMuster** [comment]
Just to have everything in one place:

PowerSave 1 uses only `wifi_sta_set_powersave(WIFI_MAX_POWERSAVE)`, this seems to have no impact on interrupts, which are needed for counting ...

**Comment by divadiow** [comment]
excellent

**Pull request merged**
