### PR TITLE
Add bme280 humidity

### PR DESCRIPTION
**Pull request by NonPIayerCharacter**
Measurement code copied from esphome.
Don't have a bme280, but bmp280 continue to work normally.
Can try to add bme680, but it is significantly different from bmx280, so the code here will not work.
So if i'm to try, am i to code it in this library, or add a new one instead?

### CODE REVIEW

**Comment by openshwprojects** [comment]
Very good, thank you! I don't have this chip as well but maybe @divadiow  has?

Regarding 680 - well, if you say it's different, then create a separate driver, you know, separate entry in drv_main.c, then a file drv_bme680, etc. You can also ask me for help anytime and I will try my best. Just make sure to put your driver disabled by default because we are trying to avoid reaching max OTA size on some platforms

**Comment by divadiow** [comment]
only BME680/BMP280 currently. will buy BME280

**Comment by openshwprojects** [comment]
What is the state of this feature? Has it been already tested? I would like to merge it but i dont have required chip at hand

**Comment by divadiow** [comment]
if it's any help, my BME280 should arrive this week

**Comment by divadiow** [comment]
image

**Comment by openshwprojects** [comment]
Thank you, I think I can merge it now

**Review by openshwprojects — APPROVED** [review]

**Comment by DeDaMrAzR** [comment]
to initiate and read BME280 use the following in your autoexec file:


// startDriver BMP280 [ClkPin] [DatPin] [OptionalTargetChannel]
startDriver BMP280 7 8 2
BMP280_Adr 0x76

**Pull request merged**
