### PR TITLE
Update constant detections in MQTT

### PR DESCRIPTION
**Pull request by avigeilpro**
Add the possibility to put a mix of text and constants in MQTT topic or values

### CODE REVIEW

**Comment by avigeilpro** [comment]
lol, as i said, i had developped this code out of context, and to follow what happened inside i had put some printf ... and of course i forgot to delete one.
Problem solved

**Comment by openshwprojects** [comment]
Was it tested on BK?

**Comment by avigeilpro** [comment]
Ok, i've just understand that i didn't need to install docker etc... to compile (sorry i'm really new on this), finally found the compile files in the pull_request and tested on BK7231N and BK7231T. Work perfectly (i've send "publish OpenBeken/${ShortName}/Update ${IP}_$Name 1" and received on mqtt broker the correct topic/value.

**Comment by openshwprojects** [comment]
Do you know that you can download binary from github PR itself? Here:
image
image

**Pull request merged**
