### PR TITLE
simple addition to allow clear text passwords for WiFi

### PR DESCRIPTION
**Pull request by MaxineMuster**
As requested here:

https://www.elektroda.com/rtvforum/topic4055720.html

### CODE REVIEW

**Comment by openshwprojects** [comment]
Thx, can you show a screenshot of how it works?

**Comment by MaxineMuster** [comment]
sure, here is a screenshot:
Bildschirmfoto vom 2024-05-22 19-08-21

**Comment by openshwprojects** [comment]
After consulting with @DeDaMrAzR , I've decided to give it a chance. If you have any futher mods, please open separate PRs, thanks!

**Comment by openshwprojects** [comment]
In future, you can try to optimize this PR change by reusing C string instead of adding it twice

**Pull request merged**
