### PR TITLE
IRsend command plus remove default pins

### PR DESCRIPTION
**Pull request by btsimonh**

### CODE REVIEW

**Comment by iprak** [comment]
@btsimonh @openshwprojects 
Local script (b.sh) to build BK2731T is failing
image

My local code is at the head
image

**Comment by btsimonh** [comment]
you need to pull the changes to the SDK(s). :).
- and then be sure to clear out your debug/obj folder....

**Comment by avdmr** [comment]
Great work! Could you please share how to use this function with an example command? Does it also work by pushing a command trough mqtt?

**Comment by btsimonh** [comment]
I guess you can trigger any command via MQTT.  @openshwprojects ?
In a couple of weeks, I'll be using the send feature to control my kitchen lights - all IR, and many (13).
For the moment I've only tested with manual command submission.
example cmnd:
IRSend NEC_0_1A

**Comment by avdmr** [comment]
Sorry for this potentially dumb question: When I receive an IR code in mqtt it looks like this: 
`IR_Sony 0x1 0x65 1`
And in the log:
`Info:IR:IR decode returned true, protocol 21
Info:IR:Address=0x1
Info:IR: Command=0x65
Info:IR: Raw-Data=0xE5
Info:IR: 12 bits
Info:IR: LSB first
Info:IR:IR decode returned true, protocol Sony (21)
Info:MQTT:Publishing val IR_Sony 0x1 0x65 0 to IRBlaster/ir/get retain=0
Info:IR:IR MQTT publish IR_Sony 0x1 0x65 0 took 1ms
Info:IR:IR fire event took 0ms
Info:IR:Received cmd 00000065
Info:IR:IR decode returned true, protocol 21
Info:IR:Address=0x1
Info:IR: Command=0x65
Info:IR:Repeat
Info:IR: Gap 25150us
Info:IR: Raw-Data=0xE5
Info:IR: 12 bits
Info:IR: LSB first
Info:IR:IR decode returned true, protocol Sony (21)
Info:MQTT:Publishing val IR_Sony 0x1 0x65 1 to IRBlaster/ir/get retain=0
Info:IR:IR MQTT publish IR_Sony 0x1 0x65 1 took 1ms
Info:IR:IR fire event took 0ms
Info:IR:Received cmd 00000065`

Do how do you convert/translate this code to be send? My first guess was:
`IRSend Sony 0x1 0x65 1`

**Comment by btsimonh** [comment]
yep, we're a little disjointed at the moment for RX vs TX.
that codes would be 
IRSend Sony_1_65

the 1 on the end indcates it is a repeat.

You CAN send repeats:

e.g.
IRSend Sony_1_65_2

but IR repeats are funny things :).  sometimes they have different values, and I'm no expert

**Comment by btsimonh** [comment]
@openshwprojects - ideally, I guess we'd want IRSend Sony 0x1 0x65 2 - but I was not sure how to do that in commands.

**Pull request merged**
