### PR TITLE
Status information auto-updates, tweaked HTML, replaces #177

### PR DESCRIPTION
**Pull request by softplus**
First steps to HTML & JavaScript changes in the UI. I'd like to update things to be a bit easier to use, potentially more consistent with Tasmota. Starting small as I figure things out in the code.

* Made the links to repo, forum thread, donation open with target=_blank (in a new tab)
* Tweaked the UI to move all the status-information (state of devices, watchdog) together (this moves the shared UI items down a bit)
* Made it possible to just request the status information via http://url/index?state=
* Made the status-information section auto-updating with JavaScript every 3 seconds
* Moved forum thread & donation link to below main UI elements
* Moved auto-submit JS from separate script to inline with input elements
* Removes URL parameters from main page after the page loads with History API (reduces chances that people will reload the page and change something unwanted)
* Hides status-update information after 5 seconds (setting values, toggles, etc.) for cleaner UI
* Added http_html_start(...) and http_html_end(...) to deduplicate & unify HTML on pages
* Tested button/relay + PWM/dimmer settings

### CODE REVIEW

**Comment by openshwprojects** [comment]
Hey, that's great and quick, I will just ask, if the radio dialog "LowMediumHigh" works here well?
https://www.elektroda.com/rtvforum/topic3895301.html
Execute command:

_setChannelType 3 LowMidHigh_
it will force firmware to use channel 3 with radio button with 3 options. Do those options works correctly?
// (3 is a channel number here, you can use any channel)
// (to clear it, use setChannelType 3 Default, if I remember correctly)

**Comment by softplus** [comment]
Thanks, that's easy enough. I wrapped all table entries in tr/td to fix the markup / forms, and tested (and fixed) all channel types. 

Display-types:
setChannelType 3 Temperature
setChannelType 3 Temperature_div10
setChannelType 3 Humidity
setChannelType 3 Humidity_div10
setChannelType 3 ReadOnly

Control-types:
setChannelType 3 LowMidHigh
setChannelType 3 OffLowMidHigh
setChannelType 3 OffLowestLowMidHighHighest
setChannelType 3 LowestLowMidHighHighest
setChannelType 3 TextField
setChannelType 3 Toggle
setChannelType 3 Dimmer

Try two at once:
setChannelType 1 Toggle
setChannelType 3 Toggle

Try three at once:
setChannelType 1 Toggle
setChannelType 2 Toggle
setChannelType 3 Toggle

Tested in code:
bRawPWMs = 0; c_pwms = 1;
bRawPWMs = 0; c_pwms = 2;
bRawPWMs = 0; c_pwms = 3;
bRawPWMs = 0; c_pwms = 4;
bRawPWMs = 0; c_pwms = 5;

**Comment by openshwprojects** [comment]
Thanks. I think I will try merging it now and check on my devices.

**Comment by openshwprojects** [comment]
seems to work great, it's very nice to see it auto-updating. But why did the buttom moved up?

image

**Comment by softplus** [comment]
That's a side-effect of using valid HTML for these elements (previously it was in the same order, but browsers showed it differently). Do you prefer the other way around? It's easy to swap.

**Pull request merged**
