### PR TITLE
Format/compress js/css

### PR DESCRIPTION
**Pull request by iprak**
So this is an attempt at making script/css more developer friendly. Writing css/script in wrapped string fields is not easy and prone to errors. It also addresses outdated "Online for" label.

**High Level Changes**
* Script/css can now be well written with meaningful comments.
* Embedded content is smaller in size, it has been minified.
* Developer will have to use [gulp](https://gulpjs.com/) after modifying js/css.
* The "Online for" is now updated on client.

** Code Changes **
* Embedded script/css have been moved out into separate files under `httpserver` folder. One can edit them, add comments.
* Minified scripts/css get injected back into `new_http.c` within marked regions. This is done using gulp package which uses [nodejs ](https://nodejs.org/en/) sub system. I use VSCode but this can done from command prompt too. After installing nodejs, one would run `npm install` to install necessary packages including gulp. All this is defined in `packages.config`.
image
* The server just sends `Time_getUpTimeSeconds` .. the js function generates the string as previously done in C.

### CODE REVIEW

**Comment by btsimonh** [comment]
thankyou for using nodejs and not python! :)

**Comment by btsimonh** [comment]
@iprak - while you are in there, could you take a look at making the 'toggled 1!' message which appears for a time after toggle not move the buttons?
e.g. move it below them?  or make it a fixed size, or position absolute?
A very small gripe :).

**Comment by iprak** [comment]
@btsimonh @openshwprojects What IDE do you use? I use VSCode. Would you object to defining tabSize of 4 spaces ? I am pretty sure other IDEs have similar settings. I see varying spaces (2 spaces, 2 tabs, 4 spaces, space+tab). I know the space/tab is a sort of a religious topic but it makes braces run all over the place. I can format some of the major files in a separate merge.

**Comment by btsimonh** [comment]
VSCode for me.
Happy to have committed VScode style files if you know how to do that....

**Comment by openshwprojects** [comment]
@iprak  what is the order of merging for your pulls?

**Comment by iprak** [comment]
#276 #278 #280
Some code formatting might be lost but that can be fixe later.

**Comment by openshwprojects** [comment]
@iprak  just to be sure, is it ready and it works with online builds?

**Comment by openshwprojects** [comment]
@iprak  ah, sorry, to answer your previous question, for OBK I am using my old MVSV 2008 but I can use a newer one if there is a ready project. I use newer MSVCs for work, also have VS Code installed

**Comment by iprak** [comment]
Yes, this does not change the VUE webApp. It only changes how some scripts work in the native webApp.

**Comment by iprak** [comment]
By the way, what is MVSV? or did you mean Microsoft Visual Studio?

**Comment by openshwprojects** [comment]
by "online builds" I meant will the binaries compiled by GitHub be ok, will Github be able to run your script.
MSVC  = 
image

**Comment by iprak** [comment]
Yes the builds should be same as before. The script/css compression was rpe-generated, nothing happens as part of the build.

VS also has formatting option. VS2019 onwards started supporting [.editorconfig](https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) file with something like this:

```
# All Language files
[*]
# Indentation and spacing
indent_size = 4
indent_style = tab
tab_width = 4
```

 You might want to upgrade to latest version, you will find the Community edition to be nicer.

**Comment by openshwprojects** [comment]
Hm ok
_/*
To edit the following two fields:
1. Edit the files script.js (pageScript) or script.css (htmlHeadStyle)
2. Generate compressed content using gulp or online compressor such as https://www.minifier.org/
For using gulp, you need to have nodejs (https://nodejs.org/en/) installed.
After that run, `npm install` at the root folder to install dependent dev packages.
And then run `gulp` which will automatically update the fields.
*/_
this needs to be in a separate readme and linked from the main readme so people know how to use

**Comment by iprak** [comment]
Can I do that as a separate merge? This repo does seem to need a page for getting started on development. Maybe a subsection in Building.md ?

**Comment by openshwprojects** [comment]
Hm ok, there are some instructions for building but if you can improve them, then that's good

**Pull request merged**
